### ISSUE TITLE
Name des Addons

### ISSUE THREAD

**Issue by schuer** [FriendsOfREDAXO/mblock#1]
Im Slack kam die Diskussion auf, ob es nicht vielleicht einen treffenderen Namen für JBlock gäbe.

* json_blocks
* Nested Slices
* Multiblock
* Frau Schultze
* …

**Comment by schuer** [comment]
Ich persönlich fände Multiblock sehr sinnvoll.

**Comment by tbaddade** [comment]
Was ein Block oder Slice ist, ist ja bereits vorgegeben. Da das AdOn nun alles innerhalb **eines** Block/Slice abhandelt, wäre ein Name wie 

* nested_slices
* sub_slices
* children_slices
* slices_in_slice

oder was auch immer. 

Leider kann man das Addon noch nicht via Installer holen. Da fällt es schwer einen passenden Namen zu finden.

**Comment by schuer** [comment]
Ich bin bei @tbaddade, allerdings sind es keine echten/gleichwertigen Blocks/Slices, sondern es handelt sich um Module, die (Formular-)Elemente enthalten können, die beliebig oft multipliziert und per Drag & Drop in der Reihenfolge verändert werden können. Sinnvoll für z. B. diverse Arten von Listen: Teammitglieder, Slider, Features, etc.

Bei Varianten von »nested slices« oder »slices in slice« würde ich als Anwender vermuten, dass ich bestehenden Module in andere Module wrappen kann, was ja leider nicht der Fall ist.

Deswegen finde ich Multiblock sinnvoll: Es handelt sich um einen Block, der beliebig viele Elemente enthalten kann. Aber es ist halt nach wie vor nur ein Block.

**Comment by joachimdoerr** [comment]
Also dann Multiblock.

**Comment by skerbis** [comment]
Ok

**Comment by joachimdoerr** [comment]
MBlock.
