### ISSUE TITLE
2ter Datenblock / löschen deaktiviert

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/mblock#10]
Hi, wenn mehrere Datenblöcke innerhalb des Moduls angelegt wurden, kann der 2te Datenblock (unterhalb des ersten) nicht mehr entfernt werden. Delete ist deaktiviert. Getestet mit dem Beispielmodul "Teammitglieder".
![mblock_test](https://cloud.githubusercontent.com/assets/189407/18121948/53c04af6-6f67-11e6-9e27-fba3763facaf.png)

**Comment by olien** [comment]
Im Modulimport steh:

> echo MBlock::show($id, $mform->show(), array('min'=>2,'max'=>4)); // add settings min and max

Ändere mal die Angabe bei "min" :-)

LG
Oliver

**Comment by darwin26** [comment]
Danke. das wars...!
