### ISSUE TITLE
Call to undefined method DOMText::getAttribute()

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#100]
mBlock 2.2.3

<img width="1184" alt="image" src="https://user-images.githubusercontent.com/330516/47963094-49b8e300-e027-11e8-968b-0c7b785103c5.png">

**Comment by joachimdoerr** [comment]
schön.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/issues/101

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/4b9f64d5cb8a1e5592d18d66209f4aee4c8b6430
