### ISSUE TITLE
Call to a member function getAttribute() on null wenn %MB_COUNT% verwendet wird

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/mblock#101]
Wenn man nach dem in Issue #55 vorgeschlagene Methode ein Accordion baut, dann wird mit MBlock 2.2.3 in MBlockBootstrapReplacer ein Fehler erzeugt:

`Call to a member function getAttribute() on null`
 
![mblock_whoops](https://user-images.githubusercontent.com/196336/47996299-6113d100-e0f8-11e8-8b6a-a717d50b890c.png)

Beispiel: `$mform->addFieldset('<a class="expertOptions " data-toggle="collapse" data-target="#accordion%MB_COUNT%">Sliderbild</a>');`

**Comment by olien** [comment]
der Fehler ist - auch ohne mForm - nachvollziehbar sofern `data-toggle="collapse"`  im Modul verwendet wird...

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/4b9f64d5cb8a1e5592d18d66209f4aee4c8b6430
