### ISSUE TITLE
Frage zu mblock:add

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#109]
Wie mache ich das: `  $(document).on('mblock:add', function (event, container,) {` richtig?

**Comment by joachimdoerr** [comment]
Ab v3.0 gibt es ein solches event nicht. MBlock nutzt einfach das rex:ready event. Du must nichts mehr machen, MBlock sollte mit allem JS fehlerfrei arbeiten welches auf rex:ready events reagiert. MBlock wirft das rex:ready event sobald ein Block hinzugefügt wird und gibt als container den neugenerierten Block mit, auf diesen werden dann die Script angewendet welche auf rex:ready hören.

**Comment by olien** [comment]
Und wie kann ich mit rex:ready auf addme reagieren?

**Comment by joachimdoerr** [comment]
das hinzufügen des blocks wirft das event rex:ready du musst mit deinen scripten auf rex:ready reagieren.

**Comment by olien** [comment]
oberen beitrag geändert

**Comment by joachimdoerr** [comment]
du musst prüfen ob der container der via rex:ready geliefert wird ein MBlock Block ist
```
$(document).on('rex:ready', function (event, container) { ...
```

**Comment by olien** [comment]
Wie geht das?

Das `$(document).on('rex:ready', function (event, container) {` habe ich ja...

**Comment by olien** [comment]
Wenn Du dazu ne Idee hast würde ich mich sehr darüber freuen!

**Comment by olien** [comment]
ok. So scheint es zu gehen...

`      $(document).on('rex:ready', function (event, container) {
                $('[data-bricky-select-a-brick] option:selected').each(function () {
                    var value = $(this).val();
                    if (value === '') {
                        $(this).closest('[data-bricky-select-a-brick]').siblings('[data-bricky-selectable]').hide();
                    } else {
                    }
                });
            });`
