### ISSUE TITLE
Wenn REX_MEDIA[] verwendet wird, erscheinen im Edit Warnings

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#11]
```
Warning: DOMElement::setAttribute(): ID already defined in /mblock/lib/classes/Decorator/MBlockFormItemDecorator.php on line 192
Warning: DOMDocument::importNode(): ID already defined in /mblock/vendors/phpQuery/phpQuery/DOMDocumentWrapper.php on line 462
```

**Comment by joachimdoerr** [comment]
Das Problem liegt hier wohl an der HTML Struktur die verwendet wurde. Tatsächlich erwartet MBlock im DOM ein "for" Element etc. Das müsste etwas aufgeweicht werden so das MBlock nicht versucht Elemente zu nutzen die es nicht gibt.

**Comment by tbaddade** [comment]
Wie muss das `for` (auch für normale Formularelemente) genau aussehen?
Was bedeutet zum Bsp. das Prefix `rv2_1_0_` in deinen HTML-Beispielen?

Könnte man  darauf nicht gänzlich verzichten?

**Comment by joachimdoerr** [comment]
Ja darauf wurde jetzt erstmal verzichtet. Es gab damit auch an anderen Stellen Probleme.
