### ISSUE TITLE
RexForm MBlock Demo

### ISSUE THREAD

**Issue by IngoWinter** [FriendsOfREDAXO/mblock#111]
Ich habe den Reiter "RexForm MBlock Demo" eben zum ersten Mal gesehen und nicht kapiert, daß das Formular in diesem Reiter tatsächlich nur das Knöpfchen `+ Press[+] to create MBlock` präsentiert. Ich finde auch die extra dafür angelegte Datenbanktabelle etwas kanonenspatzig. 
Sinnvoller als die Demo wären an dieser Stelle Erläuterung und Codebeispiele (analog zum Reiter Modul-Beispiele). Gerne mit einem Screenshot vom `+ Press[+] to create MBlock` Button, dann kann auch die Tabelle entfallen.

**Comment by tbaddade** [comment]
Bin eben auch über die Tabelle gestolpert.

@joachimdoerr Was meinst zu @IngoWinter Kommentar?

**Comment by joachimdoerr** [comment]
Ich habe das angelegt, damit es eine Demo gibt für MBlock + rexForm, am besten wäre es aber diese Demo als Plugin auszulagern, so das man sie bedarfsgerecht installieren kann und somit die Tabelle nicht per default im system hat.

**Comment by tbaddade** [comment]
Heute wieder darüber gestolpert :)
Eventuell kann man es auch in der [Modulsammlung](https://github.com/FriendsOfREDAXO/Modulsammlung) mit aufnehmen? 
Vielleicht ist es auch schon dabei. @olien kannst du was zu sagen?

**Comment by olien** [comment]
Ist nicht dabei Block und RExForm kenne ich gar nicht... gibt es ein Beispiel, welches ich in die Modulsammlung packen kann?
