### ISSUE TITLE
rex:ready Event beim Sortieren

### ISSUE THREAD

**Issue by fietstouring** [FriendsOfREDAXO/mblock#112]
beim Hinzufügen neuer Blöcke wird ein rex:ready getriggert aber nicht beim Sortieren.
wenn Ihr da auch den Event triggern könntet, wäre super, da können die Editoren darauf reagieren. In meinem Fall hab ichs für CKEditor 4 hinbekommen, dass Sortieren über die Pfeile funktioniert.

**Comment by joachimdoerr** [comment]
rex ready ist hier aber das falsche event das würde zu reinits führen

**Comment by fietstouring** [comment]
Dann ein anderer event, jedenfalls muss der editor vor dem reindex zerstört und dann wieder initialisiert werden, sonst gehts nicht

**Comment by joachimdoerr** [comment]
dann müssen wir also wieder eigenen MBlock events einziehen was eigentlich genau das ist was ich abschaffen wollten.

**Comment by fietstouring** [comment]
soweit ich das getestet gibts momentan zwei Editoren bei denen es ohne Events geht und zwei, die Probleme haben, d.h. mit denen man mblock quasi nicht verwenden kann, da kein Sortieren möglich.

**Comment by skerbis** [comment]
Könnte core-seitig ein neues event rex:slice_updated oder ähnliches helfen? Ich denke das wäre nützlich und allgemeiner?

**Comment by tbaddade** [comment]
> Könnte core-seitig ein neues event rex:slice_updated oder ähnliches helfen? Ich denke das wäre nützlich und allgemeiner?

Ich vermute es geht um das Verschieben der einzelnen MBLöck innerhalb **eines** Slices.

**Comment by fietstouring** [comment]
> > Könnte core-seitig ein neues event rex:slice_updated oder ähnliches helfen? Ich denke das wäre nützlich und allgemeiner?
> 
> Ich vermute es geht um das Verschieben der einzelnen MBlöcke innerhalb **eines** Slices.

Das ist richtig.

**Comment by skerbis** [comment]
@tbaddade ja. Darum geht es. Ich dachte hier in diesem Fall wäre es vielleicht sinnvoll ein allgemeines event zu haben, dass anderen Skripten mitteilen kann dass sich der slice verändert hat. So dass z.B. Editoren, Picker etc.  darauf reagieren können und sich neu initialisieren können.

**Comment by joachimdoerr** [comment]
ein allgemeines event wäre aus meiner Sicht auch wesentlich sinnvoller als wieder MBlock spezifische events zu konstruieren

**Comment by tbaddade** [comment]
Diese Pfeile bei den Blöcken von MBlock gehören zu MBlock und da müsste doch MBlock ein Event liefern.

> dass anderen Skripten mitteilen kann dass sich der slice verändert hat

verändert hat sich der Slice erst, wenn auch tatsächlich gespeichert wurde. Ansonsten würde das event bei jeder Eingabe eine Zeichen doch getriggert werden.

**Comment by fietstouring** [comment]
> verändert hat sich der Slice erst, wenn auch tatsächlich gespeichert wurde. Ansonsten würde das event bei jeder Eingabe eine Zeichen doch getriggert werden.

da muss ich ziemlich klar zustimmen

**Comment by joachimdoerr** [comment]
ja auch wenn es mblock elements sind und es eine mblock Sortierung ist möchten wir gerne ein allgemeines redaxo genauso wie `rex:ready` meinetwegen `rex:change` das dann von allen möglichen resource genutzt werden kann. das sorgt dann dafür, dass die resource nicht mblock supporten müssen sondern nur die allgemeinen events. ist bekannt dass man bei DOM änderungen eine destroy benötigt kann man auf das event hören, den content des events durchlaufen, destroyen und ein reinit fahren.

**Comment by joachimdoerr** [comment]
0ebfed61859eb535fb1359c1e6bd954e4919dc13

**Comment by fietstouring** [comment]
Danke! der event müsste aber **vor** dem Reindex kommen, weil der Editor zuvor zerstört werden muss. Nach dem Reindex ist der Inhalt im Editor verloren. Bei mir funktioniert das nur wenn der event ausserhalb des timeout kommt (mblock_moveup bzw. _down)
