### ISSUE TITLE
validate blockiert speichern/übernehmen

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/mblock#116]
Hi,
würde gerne die Validate von MForm/MBlock in den einzelnen Feldern nutzen.
Aber sobald ich diese (z.B. mit "empty") eintrage, werden die Felder zwar vaildiert (rot/grün),
jedoch ist dann kein speichern/übernehmen des Blocks mehr möglich ... klick zeigt keine wirkung.

ich teste aber nochmal ausführlich mit einem blanken modul; und berichte

MFORM:  5.2.4
MBLOCK: 3.1.0

**Comment by joachimdoerr** [comment]
@darwin26 kannst du ein Beispiel geben?

**Comment by alxndr-w** [comment]
Hab's nicht nachstellen können.
