### ISSUE TITLE
Duplizier-Button zusätzlich zum "+"

### ISSUE THREAD

**Issue by bitshiftersgmbh** [FriendsOfREDAXO/mblock#117]
Aktuell kann man mit dem Replizier-Algorithmus Blöcke definieren, die mit einem "+" in der Headline jeweils nach unten um einen neuen Block erweitert werden. Ich nutze das ganze Konstrukt immer öfter, da es sehr gut handhabbar, selbsterklärend und im Backend platzsparend ist.

Entsprechend hat man auch oft den Fall, dass man eine ganze Reihe Blöcke hintereinander schaltet, bei denen die Mehrheit der Einstellungen identisch ist und oft nur 1 oder 2 Felder verändert wären.

Da wäre eine Duplizierfunktion richtig klasse. Einfach als zusätzlicher Button neben dem "+". Als Icon empfehle ich https://fontawesome.com/icons/copy?style=regular oder https://fontawesome.com/icons/clone?style=regular .
Es sollten wenn dabei möglich alle Einstellungen von Inputs und Widgets (soweit machbar) in den neuen Block übertragen werden. Duplizieren eben. :)

**Comment by joachimdoerr** [comment]
Gefällt mir. Das könnte man leicht Via JS anbieten, so funktionierte MBlock ja ganz zu beginn.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/363dc69d64d47ae9bea5c42072c2e45f4635d54b
