### ISSUE TITLE
Blockauswahlliste für "+"-Button denkbar?

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/mblock#118]
Hallo Leute,

wäre es denkbar, für den "+"-Button eine Auswahlliste erstellen zu können, wo vordefinierte Blöcke bereitstehen?

Bei Typo3 und Contao ist es z.B. möglich, die bestehenden Pflegemodule in sich selbst zu integrieren, so dass man z.B für eine mehrspaltige Darstellung sich die gewünschten Blöcke je Spalte selbst zusammenstellen kann.

**Comment by joachimdoerr** [comment]
Das ist eine extrem komplexe Anforderung. Es wäre schon machbar. Ggf. durch das integrierte Formular welches in diverse Segmente aufgeteilt sein könnte die je nach Auswahl dann erscheinen. Verwaltet durch MBlock selbst sehe ich das erstmal nicht als mögliche Option dafür müsste man MBlock komplett neu bauen.

**Comment by joachimdoerr** [comment]
Die frage ist ja auch ob das nicht Overkill ist. Ist MBlock für sowas wirklich das richtige?

**Comment by iceman-fx** [comment]
Es wäre auf jeden Fall eine besondere Möglichkeit, welche so nicht allzu viele CMS bieten und der Bediener sehr umfangreiche Gestaltungsmöglichkeiten bekommen könnte.
