### ISSUE TITLE
Zählweise bei MB_COUNT

### ISSUE THREAD

**Issue by pschuchmann** [FriendsOfREDAXO/mblock#119]
Ich habe eben mal ein wenig getestet mit dem MB_COUNT. 

```
$mform->addHtml('%%MB_COUNT%%');
```
zählt bei mir korrekt hoch.

 Verwende ich
```
$mform->addHtml('%MB_COUNT%');
```
stimmt der erste Index noch, der Zweite zählt runter und bleibt dann bei 0. Schätze, dass war so nicht beabsichtigt, oder? Oder funktionieren die beiden Platzhalter einfach unterschiedlich?

**Comment by joachimdoerr** [comment]
Müsste ich selbst mal nochmal testen. Das muss sowieso komplett überarbeitet werden für MBlock 4.
