### ISSUE TITLE
Inhalte gehen verloren

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#12]
Wenn ein REX_MEDIA nachträglich vor allen anderen Formelemente im Modul eingetragen wird, ist zum Bsp. ein textarea leer geblieben, obwohl Inhalt drin waren.

**Comment by tbaddade** [comment]
Auch beim verschieben der Elemente innerhalb des Moduls gehen dann beim editieren Inhalte verloren.

**Comment by joachimdoerr** [comment]
Passiert das beim speichern? Oder nur bei Javascript Aktionen (add, remove, move up or down)?

**Comment by tbaddade** [comment]
Beim aufrufen des Slices. Also man ändert nachträglich das Modul, geht in den Artikel und will den Slice editieren.

**Comment by joachimdoerr** [comment]
Ja das ist besonders schwer, da ja die values aus der DB auf das Formular passen sollten ...

**Comment by joachimdoerr** [comment]
Ich kann das leider nicht nachstellen, ggf. gibt es Probleme mit sonstigen Javascript-Bibliotheken?

**Comment by tbaddade** [comment]
Hmm … recht Voodoo … Nachstellen kann ich es heute auch nicht mehr. Gestern war es mehrmals definitiv vorhanden. Ich schließe mal das Issue und können es ggf. wieder öffnen
