### ISSUE TITLE
Linklist Feld: Artikel Id wird nicht angezeigt

### ISSUE THREAD

**Issue by dtpop** [FriendsOfREDAXO/mblock#121]
Bei der Auswahl von Links wird die Artikel-Id der entsprechenden Artikel korrekt angezeigt.
Wenn das Feld wieder zur Bearbeitung geöffnet wird, fehlen die Artikel-Ids.
Die umkringelten Links sind grade rein geklickt, die nicht umkringelten waren schon drin als der Block zur Bearbeitung geöffnet wurde.

![Unbenannt](https://user-images.githubusercontent.com/1282121/58586078-916cb980-825a-11e9-8393-4b1ce1bd95ba.JPG)

**Comment by joachimdoerr** [comment]
Ja sollte dann mit MBlock 4 behoben sein.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/6a04cabdc9901bd049f3340ced4d6501ce906bc1#diff-e9fd8ca78bc7180081f53a3b9d9b646aR383
