### ISSUE TITLE
docs: Keinen Block in der Moduleingabe ausgeben, wenn min=0

### ISSUE THREAD

**Issue by alxndr-w** [FriendsOfREDAXO/mblock#122]
Bei der Moduleingabe kann es vorkommen, dass auch kein MBlock erwünscht ist. Dazu habe ich min=0 eingestellt. Es wird dennoch ein MBlock ausgegeben, den ich manuell entfernen kann.

Beim nächsten Editieren wird jedoch wieder ein MBlock angezeigt und abgespeichert, wenn man nicht darauf achtet, diesen wieder von Hand zu löschen.

min=0 sollte standardmäßig das Interface laden ohne mblock, nur mit dem +-Zeichen.

**Comment by skerbis** [comment]
Verstehe ich nicht

**Comment by alexplusde** [comment]
Ich mach einen Screencast...

**Comment by skerbis** [comment]
min=0 ist irgendwie sinnlos

**Comment by alexplusde** [comment]
Der Screencast ist unterwegs, dann wird es klar ;)

**Comment by skerbis** [comment]
Ich denke ie Problematik ist Dir nun klar. Tatsächlich ist die Möglichkeit min=0 eher ein Bug.

**Comment by alexplusde** [comment]
Ich finde, alle Werte eines Formulars leer lassen ist mit dem gezeigten Beispiel nicht so gut und ein workaround, nicht eine Lösung. Aber mit dem workaround komme ich auch klar in meinem Fall

**Comment by isospin** [comment]
hab gerade auch danach gesucht und es in einem alten projekt wiedergefunden:

`echo MBlock::show(1, $mform->show(), ['initial_hidden' => 1, 'min' => 0, 'initial_button_text' => 'Press [+] to create MBlock']);`

**Comment by alexplusde** [comment]
Sollte dann dokumentiert werden.
