### ISSUE TITLE
Statt Icons für Papierkorb und Plus-Zeichen: Buttons beschriften

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mblock#123]
Siehe: https://github.com/redaxo/redaxo/issues/2706

Plus-Zeichen ergänzen mit "neuer Abschnitt", Papierkorb mit "Abschnitt löschen"

**Comment by skerbis** [comment]
Ich möchte ungerne einen Bruch mit der gewohnten Ui hier.

**Comment by skerbis** [comment]
Gerne ein eigenes Theme per PR

**Comment by joachimdoerr** [comment]
Das könnte man via Theme lösen, in MBlock4 werden die auf fragmente umgestellt, ggf. könnte man sowas auch via settings ins default Theme integrieren.

**Comment by joachimdoerr** [comment]
Sehe ich aber erstmal nicht als nötig an, ich werde definitiv nicht dazu kommen das einzuziehen. gerne als PR. Sonst schließe ich hier.
