### ISSUE TITLE
Kleiner Schreibfehler in der Verwaltung

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/mblock#127]
![image140](https://user-images.githubusercontent.com/4291047/72883823-4e89b580-3d05-11ea-8972-d9ca502e05fb.png)

Soll sicher "Blöcken" anstatt "Blocken" heißen ;-)

**Comment by joachimdoerr** [comment]
Stimmt.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/9272b3414c19d60af300131f83599b0fe6ac2c08
