### ISSUE TITLE
Testfälle

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mblock#128]
MBlock-MForm Tests aus den MForm-"Basis Beispielen": 

- [ ] Text-Input- und Hidden-Elemente
- [ ] Select- und Multiselect-Elemente
- [ ] MForm-Widget-Elemente
 
- [ ] Checkbox und Radio-Elmente
- [ ] Strukturelle Inline-Elemente
- [ ] System-Button-Elemente
Bitte beim Custom-Link Widgets alle Optionen Testen siehe: https://github.com/FriendsOfREDAXO/mform/blob/master/lib/MForm/MFormElements.php#L600

MBlock-MForm Tests aus den MForm-"Erweiterte Beispiele": 

- [ ] Attributes Method
- [ ] Options Method
- [ ] Parameter Method
- [ ] Full JSON-Value-Support
- [ ] Wrapper-Elemente

MBlock-MForm Tests aus den MForm-"Experten Beispiele":

- [ ] Neue HTML5 Formular-Elemente
- [ ] Datalists für Input-Elemente
- [ ] Placeholder
- [ ] Parsley Validation

Wie vorgehen? 

1. MForm Master von GitHub downloaden
2. MBlock [V4/Brnach](https://github.com/FriendsOfREDAXO/mblock/tree/feature/mblock4) von GitHub downloaden
3. Beide Addons installieren und die MForm-Beispiele Module nutzen zum testen
4. Natürlich jedes Beispiel Modul entsprechend als MBlock Variante anlegen
5. Testen und ggf. vorhandene Fehler hier Reporten
6. Wenn der Test für ein MBlock-MForm Beispiel Modul gut gelaufen ist in der Checkliste oben abhacken.

MBlock extra Tests:

- [ ] Max - Min option testen
- [ ] MBlock initialisieren Button und Button Text testen
- [ ] MBlock für yForm und rexForm testen
- [ ] Alle Testmodule auch als Nested-MBlocks testen (ggf. neues Testfall issue dafür anlegen)
- [ ] @joachimdoerr weitere Testfälle definieren

**Comment by MargadantLuca** [comment]
Hallo zusammen,

Ich könnte das gerne mal durchtesten. Unter anderem auch, weil ich mich persönlich sehr auf den Release 4 freue. 

Könntet ihr mir für die «MBlock extra Tests» allenfalls noch mitteilen, wie ich einen nested Mblock hinzufügen kann?

**Comment by IngoWinter** [comment]
Gibt es irgendwo eine Übersicht der Änderungen zu mblock 3? Ich habe gerade festgestellt, dass Media Widgets mit dem alten numerischen Key nicht kompatibel zu 4 sind, weil sie alles andere überschreiben :)
Wo halte ich solche Beobachtungen fest? Neues Issue aufmachen und irgendwie als mblock 4 kennzeichenen?
