### ISSUE TITLE
sortable function umbenenen

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/mblock#13]
nur zur Erinnerung, weil die Diskussion ja in einem anderen issue lief...

Dein mblock überschreibt die sortable Funktion der jquery-ui.custom.min.js des REDAXO Backends - 
du wolltest deine Funktion umbenennen.

**Comment by joachimdoerr** [comment]
Danke.

**Comment by joachimdoerr** [comment]
Done. https://github.com/FriendsOfREDAXO/mblock/commit/c50ee0cb82eff78c5bcede8fba38e486f6bf4f39 bitte noch testen
