### ISSUE TITLE
REX_LINK nicht nutzbar (Schreibweise)

### ISSUE THREAD

**Issue by rene-mueller** [FriendsOfREDAXO/mblock#132]
Es ist ein mir ein Fehler bei einem Modul aufgefallen. Es scheint so als ob es ein MBlock Fehler ist: https://github.com/redaxo/redaxo/issues/4588 

**Description / Beschreibung**
ich habe in einem Modul REX_LINK verwendet. Nachdem ich einen Link über den Button im neuen Fenster auswählen wollte, bekomme ich in der Konsole den folgenden Fehler:

![image](https://user-images.githubusercontent.com/48084558/112520699-fb454400-8d9b-11eb-88fd-236c9b6f9e20.png)
![image](https://user-images.githubusercontent.com/48084558/112499558-e363c500-8d87-11eb-8565-8411c8bf5025.png)

PS: Der Link wird nicht im Formularfeld gesetzt.

**Comment by DanielWeitenauer** [comment]
Es ist nicht direkt ein Fehler, eher unintuitive DX.
Die Elemente mit REDAXO-Widgets REX_LINK und REX_MEDIA müssen innerhalb von MBlock mit Zahlen referenziert werden.
Statt `$mForm->addLinkField("$id.0.buttonLink");` muss es `$mForm->addLinkField(1);` wie beim Einsatz ohne MBlock lauten. Das liegt daran, wie REDAXO die Widgets erzeugt.

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/mform/issues/230#issuecomment-879740700

**Comment by alxndr-w** [comment]
@rene-mueller wäre es möglich, dass du hier noch die Ergebnisse nimmst und in die Doku packst? Sonst würde ich hier zumachen.

**Comment by rene-mueller** [comment]
@alxndr-w würde ich gerne machen, habe nur keinen Zugriff mehr auf die Informationen, da ich nicht mehr bei der Firma arbeite und leider den Kontext dazu nicht mehr weiß.

**Comment by alxndr-w** [comment]
@rene-mueller Steht eigentlich in der Antwort von @DanielWeitenauer. Aber ja, nach 3 Jahren weiß ich auch nicht mehr, was meine Issues sind.

Dann mache ich hier zu.
