### ISSUE TITLE
Mblock 3.1.0 - Widgets in REDAXO 5.12.1 defekt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mblock#137]
Die Medienauswahl funktioniert nicht mehr. 

> geändert haben sich die onclick attribute
onclick="addREXMedia(1, '...')"  etc.
da sind jetzt neu anführungszeichen um die id vorne.
yform hat den js-code in onclick per regex angepasst, und das passte daher nicht mehr.
weiß nicht, ob das vielleicht auch in mblock das problem ist

Gregor hat folgenden Lösungsvorschlag geliefert: 

für die Zeilen 172 und 195 in mblock.js

```
$(this).attr('onclick', $(this).attr('onclick').replace(/(\('?)\d+/, '$1' + sindex + '' + mblock_count + '00' + eindex));
```
Das funktioniert ab dem 2. Block. 

in YForm wurde es wie folgt gelöst: 

https://github.com/yakamara/redaxo_yform/commit/ce6394769e2daae55e297b73fcebb5ea7226a2ea

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/0a7c570ea30e448fe692d1df5fd9e90c7b8aadfd

Das Problem sollte mit dem Commit behoben sein.

**Comment by shauste** [comment]
Konnte das Problem leider nicht lösen durch das Abändern der o.g. Zeilen – „Datei übernehmen“ ist nicht möglich.

Ausgabe Konsole:
`Uncaught TypeError: Cannot set property 'value' of null
    at selectMedia (mediapool.js?buster=1624340028:232)
    at HTMLAnchorElement.onclick (index.php?page=mediapool/media:245)`

**Comment by joachimdoerr** [comment]
Hier fehlte der PHP Part für die Initialvergabe der oncklick tags in den Widgets, das JS replacement greift nur im Falle der Duplizierung. Mit dem letzten Commit sollen nun alle System-Widgets wieder laufen. https://github.com/FriendsOfREDAXO/mblock/commit/77d83f6a8f685285e0589242aad25b7ae59f7b79

**Comment by shauste** [comment]
@joachimdoerr Konnte ich testen, klappt.

**Comment by steri-rex** [comment]
danke - hat bei mir auch geklappt!
