### ISSUE TITLE
 Block-Count-Ersetzungs-Key

### ISSUE THREAD

**Issue by site-concept** [FriendsOfREDAXO/mblock#14]
Ein Ersetzungs-Key mit fortlaufender Nummer wäre hilfreich. So könnten z.B. Tabs/Reiter innerhalb von Blöcken aufgebaut werden.
z.B:
`$objForm->addHtml('<li><a href="#tab{%BLOCK-COUNTER%}" data-toggle="tab">Tab 1</a></li>');`

**Comment by joachimdoerr** [comment]
ja das macht sinn nur müsste das mform javascript auch wissen, dass es counten muss. und wo es Counter muss.

das wäre dann eher `data-count-target="id" data-count-prefix="#tab-" data-count-suffix="-index"`

**Comment by site-concept** [comment]
Ich habe es für mich kurzfristig "Quick and Dirty" gelöst, indem ich die Zeile 79 in der show methode angepasst habe

`static::$output[] = str_replace("###UNIQID###", uniqid(), MBlockParser::parseElement($element, 'element'));`

Damit hat jedes Element eine ID, die ich benutzen kann, damit komme ich erstmal zurecht.

**Comment by IngoWinter** [comment]
#15 sollte das eigentlich erschlagen.

**Comment by joachimdoerr** [comment]
close.
