### ISSUE TITLE
Wunsch: einen "+"-Button ganz oben, um einen neuen ersten Eintrag anzulegen

### ISSUE THREAD

**Issue by iceman-fx** [FriendsOfREDAXO/mblock#141]
Es wäre toll, wenn man vor dem ersten Eintrag (Item) auch einen neuen Eintrag anlegen könnte.
Derzeit erfolgt dies immer unter dem ersten Eintrag.

**Comment by eaCe** [comment]
Da kein Feedback gegeben wurde mache ich hier zu. Gerne wieder öffnen, wenn Feedbacm vorhanden

**Comment by tbaddade** [comment]
Nur als Idee für @joachimdoerr 

Wir hatten das Bei YForm für Inline Relationen mal so gelöst, dass nach Klick auf ein `+` immer oberhalb eine neuer Block hinzugefügt wurde.

<img width="436" alt="Bildschirmfoto 2023-12-11 um 08 46 02" src="https://github.com/FriendsOfREDAXO/mblock/assets/338267/0285f585-3db9-4905-94be-52db4578161e">
