### ISSUE TITLE
addMedialistField bug in Mblock

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mblock#146]
Moin Joachim,
ich nutze seit Ewigkeiten `$mblock->addMedialistField(1, array('label' => 'Bilder'));` in Mblock. Das hat immer gut funktioniert. Jetzt ist im Slack aufgefallen dass in aktuellen Versionen das ganze nur ab 2 Blöcken funktioniert. Mit einem Block wird der Medienpool nicht geöffnet.
Bei Rex 5.11.0 Mblock 3.1.0 Mform 5.3.1 funktioniert es noch tadellos. ich kanns nicht nachvollziehen leider ;-(

**Comment by marcohanke** [comment]
@joachimdoerr Ich habs isoliert. Alle Updates laufen, der Fehler tritt auf beim aktualisieren auf Redaxo 5.13.0

**Comment by eaCe** [comment]
@marcohanke hast du die aktuelle mblock version getestet 3.1.0 ist ja schon was älter? Soweit ich mir erinnere hatten wir dieses Problem und @skerbis hat das hier gefixed: https://github.com/FriendsOfREDAXO/mblock/releases/tag/3.4.1

**Comment by marcohanke** [comment]
Hey @eaCe Ich hab es mit allerlei Versionen probiert, natürlich auch mit den aktuellsten Versionen. Es funktionieren alle Versionen nur nach Update auf Rex 5.13.0 funktioniert nichts mehr.

**Comment by eaCe** [comment]
@marcohanke also ich habe hier mblock  3.4.1 mit mform 6.1.0 und es funktioniert mit `$mform->addMedialistField(1, array('label' => 'Bilder'));` ganz problemlos. 
Bekommst du irgendwelche Fehler in der Console?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/a78926c4798bf84e5a81bee267b6ae0b767d20dd

**Comment by eaCe** [comment]
@skerbis man gerade habe ich es auch gefunden...
https://github.com/FriendsOfREDAXO/mblock/blob/master/lib/MBlock/Replacer/MBlockSystemButtonReplacer.php#L178
