### ISSUE TITLE
Falscher Tooltip beim Hinzufügen-Button für weiteren MBlock-Eintrag

### ISSUE THREAD

**Issue by ischfr** [FriendsOfREDAXO/mblock#153]
Wenn man im Backend einen Artikel-Block mit MBlock-Einträgen editiert und einen neuen MBlock-Eintrag hinzufügen möchte, dann erscheint beim Plus-Button als Tooltip "Duplicate" statt z.B. "Add" oder "New".

Ausserdem sind die Tooltips immer in englisch beschriftet und nicht in der aktuellen Backend-Sprache.

Schön wäre es, wenn sich die Beschriftung und Sprache der MBlock-Tooltips sich an den Tooltips der regulären Artikelblöcke orientieren könnte.

**Comment by alxndr-w** [comment]
Leider kein PR erhalten.
