### ISSUE TITLE
Values in Inputs mit type="hidden" werden gelöscht

### ISSUE THREAD

**Issue by DanielWeitenauer** [FriendsOfREDAXO/mblock#164]
Das Value-Attribut in Input-Feldern mit type="hidden" wird von MBlock geleert. 
Der vorgegebene Wert sollte aber bestehen bleiben.

**Affected versions / Verwendete Versionen**
MForm 7

**Comment by alxndr-w** [comment]
@DanielWeitenauer möchtest du dich dem noch annehmen? Sonst würde ich hier schließen.

**Comment by alxndr-w** [comment]
Evtl. taugt der neue MForm-Repeater dazu auch.

**Comment by skerbis** [comment]
@alxndr-w @DanielWeitenauer fixed
