### ISSUE TITLE
MBlock als Value Type in YFORM?

### ISSUE THREAD

**Issue by cukabeka** [FriendsOfREDAXO/mblock#167]
Ich bin auf der Suche nach einer Möglichkeit, sowas wie Modul Slices in YForm ablegen zu können. Tatsächlich würde für mich auch funktionieren, wenn man MBlöcke in YForm als Feldtyp nutzen könnte. Es gibt ja schon die Möglichkeit andersherum. Wäre denkbar, MBlock auch in YForm nutzbar zu machen? Ich kann das nicht gut einschätzen.

**Comment by tbaddade** [comment]
Kannst du via `be_manager_relation` Value erreichen

Bei der `Mehrfachauswahl` müsstest du` 1-n (inline)` auswählen.

Sieht dann so aus:

<img width="1244" alt="Bildschirmfoto 2024-10-01 um 08 16 33" src="https://github.com/user-attachments/assets/f48aa234-a02d-4485-9257-3ca71b09f8e8">

Der Screen hat doppelte Inline-Relationen. Speichert hier somit in drei Tabellen.
