### ISSUE TITLE
Blocks als Reiter / Tabs

### ISSUE THREAD

**Issue by tyrant88** [FriendsOfREDAXO/mblock#17]
Das fände ich gut...
Ich weiß, bei 12 Tabs sieht es wahrscheinlich Mist aus, aber bis dahin....

**Comment by joachimdoerr** [comment]
Ja kann man machen ist aber nicht trivial, wie sollen die Tabs benamst werden? Und dann müsste das ja auch sortierbar sein, mit Tabs ist das auch nicht so easy, da müsst ein entsprechendes Javascript her.

**Comment by tyrant88** [comment]
Wenn es trivial wäre, hätte ich mich schon selbst dran versucht ;;;;;-)
Bennennung? Vielleicht "Block 1", "Block 2" ? :-)
Sortierbar sind sie doch auch jetzt schon, oder?
Als Akkordion, bzw collapsable, also zusammenfalten bis auf die Headline vielleicht? Das würde doch auch schon mehr Übersicht bringen, oder?

**Comment by skerbis** [comment]
Wie meint Ihr das? Mblock-Abschnitte in Tabs oder die mblocks selbst noch mal in Tabs aufteilen?

**Comment by tyrant88** [comment]
Also ich hab z.B. ein Akkordeon-Modul mit mblocks gemacht: immer Akkordeon-Überschrift und -Text als ein mblock-Formular in der Eingabe. Wenn es mehrere sind und der Text etwas länger ist, sitzt das ja alles untereinander und deshalb hätte ich die einzelnen mblock-Formulare gerne auf Reitern.

**Comment by joachimdoerr** [comment]
Da wird die Reiter Liste dann auch ziemlich lange... eine Art Panel oder Accordion Mode für MBlock wäre da doch sinnvoller oder?

**Comment by joachimdoerr** [comment]
Ich werd das hier mal schließen da ich in Zukunft keine Tabs für MBlock plane, der Aufwand dafür wäre sehr hoch.
