### ISSUE TITLE
Sonderfall: null Blöcke

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mblock#18]
`array('min'=>0,'max'=>5))`

leere mblocks werden trotzdem gespeichert. Wenn ich sie ganz entferne, tauchen sie beim nächsten editieren wieder auf, was ja auch gut ist, sonst könnte man sie ja gar nicht mehr bearbeiten.

Das hat zur Folge, dass leer abgespeicherte Blöcke beim nächsten editieren noch ein weiteres leeres mblock hinzufügen.

Zu erwarten wäre, dass dann nur ein leeres mblock dargestellt wird und leere mblocks nicht mit gespeichert werden.

**Comment by joachimdoerr** [comment]
Naja, was man entfernt haben will sollte man mit dem "-" Button löschen. Aber dass sobald ein leerer Block vorhanden ist ein weiterer leerer Block plötzlich beim editieren auftaucht sollte nicht so sein, das muss ich mir mal genau anschauen.

**Comment by joachimdoerr** [comment]
Bei meinen Tests ist in dem Fall konnte ich jetzt nicht nachstellen, dass nach dem man den letzten Block entfernt hatte, nochmal editieren wollte mehr als ein leeres MBlock Feld erschien. Auch nach erneutem "leer" Speichern ohne das Feld nochmals komplett zu entfernen ist beim erneuten editierversuch kein zweites MBlock Feld erschienen.

**Comment by alexplusde** [comment]
Ich schau's mir nochmal an mit einem aktuellen mblock

**Comment by joachimdoerr** [comment]
Und hast du schon was rausgefunden?

**Comment by joachimdoerr** [comment]
Können wir hier schließen?

**Comment by alexplusde** [comment]
Gerade getestet, passt.
