### ISSUE TITLE
Master Module - mblocks über Module hinweg verwenden.

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mblock#19]
Wäre klasse, wenn man nicht nur Module innerhalb von mblock definieren könnte, sondern auch auf die regulären Module Zugriff hätte oder Master-Module hätte.

So muss man Code ja ggf. doppelt führen, bspw. ein Download-mblock in einem `mblock-Modul 1` und ein Download-mblock in einem `mblock-Modul 2`

**Comment by joachimdoerr** [comment]
Hab ich noch nicht so ganz kapiert. 
Entweder dein Modul bietet die Möglichkeit Blöcke mit MBlock zu duplizieren oder nicht.

**Comment by skerbis** [comment]
Er wünscht sich eine Art Modul-Templating, denke ich. Wiederverwendbare Mblock-Blöcke, die irgenwo zentral gespeichert sind. So dass er diese nach Belieben mit Mblock kombinieren kann.

**Comment by alexplusde** [comment]
Was @skerbis sagt. :) 

Weitergedacht wäre es so, dass man dann verschiedene MBlock-Templates innerhalb eines MBlocks hinzufügen kann (bspw. ein Text-Mblock, dann ein Download-Mblock, dann wieder ein Text-Mblock). Dann entspricht ein mblock quasi einem ctype, nur eben innerhalb eines Moduls. (Eine entsprechende Funktionalität wird sich ja seit jeher an Redaxo-Tagen gewünscht, um mehrspaltige Layouts mit unterschiedlichen Inhalten umsetzen zu können).

**Comment by skerbis** [comment]
@alexplusde 
Das müsste auf CORE-Ebene erfolgen. Das Verwalten der Module/Blöcke müsste dann ganz anders erfolgen. Du möchtest eine Grid Lösung. Die kann man so nicht bauen. 
Ohne eine Lösung für das Frontend-Editing (z.B. DIVI oder Elementor für Wordpress)  ist es aus meiner Sicht auch nutzlos. Grid-Design kann nur funktionieren, wenn Du live das Ergebnis siehst. 
Theoretisch benötigt man in Redaxo die Möglichkeit Wrapper-Elemente wie Sections und Rows zu erzeugen in denen dann die Blöcke abgelegt werden. Aber ein Mblock bleibt ein Block.

**Comment by joachimdoerr** [comment]
@alexplusde sich sehe das wie @skerbis schon schreibt, die Idee von MBlock ist recht banal und sollte es auch bleiben. Ich kann den Wunsch zwar verstehen aber MBlock ist da eher das Falsche Addon um das zu realisieren. Gegenwertig soll MBlock nichts anderes als die Lücke schließen, dass man in einem Modul-Block bestimmte Eingaben blockweise duplizieren kann.

**Comment by alexplusde** [comment]
OOOOOOkkaaaaaay :) Dann träume ich mal weiter :D

**Comment by joachimdoerr** [comment]
close.
