### ISSUE TITLE
textarea und &-Zeichen: unterminated entity reference Tag

### ISSUE THREAD

**Issue by darwin26** [FriendsOfREDAXO/mblock#20]
Hi,
ich habe mform/mblock mal getestet und dabei dem textarea die class: redactorEditor2-simple verpasst. In der EIngabe mit einem &-Zeichen erscheint folgender Fehler:

Warning: MBlockFormItemDecorator::replaceValue(): unterminated entity reference Tag 
/redaxo/src/addons/mblock/lib/classes/Decorator/MBlockFormItemDecorator.php on line 121

Fehler tritt mit und ohne redactor2 im textarea auf ...
Danke. Gruß Chris

**Comment by darwin26** [comment]
auskommentieren hilft... sollte aber nicht die Lösung sein
`/*
                case 'textarea':
                    if ($matches && array_key_exists($matches[1], $item->getResult())) $dom->nodeValue = $item->getResult()[$matches[1]];
                    break;
                */`

**Comment by darwin26** [comment]
auskommentieren hilft.. is aber nicht die lösung

`/*
case 'textarea':
if ($matches && array_key_exists($matches[1], $item->getResult())) $dom->nodeValue = $item->getResult()[$matches[1]];
                    break;
*/`

**Comment by darwin26** [comment]
... scheinbar tritt es nur mit blanken textareas und redactor2-textareas auf ...
habe das Problem (&-zeichen) nun mit dem TinxMCE4 AddOn + textarea nicht mehr...

**Comment by joachimdoerr** [comment]
Hm kann ich leider nicht nachstellen. Browser Betriebssystem? Beim anlegen eines blanken MBlock Moduls oder bim Editieren?

**Comment by darwin26** [comment]
es war, fehler tritt nicht mehr auf (warum auch immer)
... sry. close

_(OSX / FF. 49.0.2 / Beim mehrfach Anlegen der mblock's und erstbefüllen der textarea ...)_
