### ISSUE TITLE
Dynamische Headlines (legend)

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/mblock#22]
Ich hätte gerne zur besseren Übersicht, dass man im <legend> Platzhalter nutzen könnte. Dabei gehts mir vorallem um den Slice-Counter, damit z.B. <legend> Spalte #X</legend> möglich ist.

**Comment by joachimdoerr** [comment]
Ein wichtiges Feature das macht definitiv sinn.

**Comment by joachimdoerr** [comment]
done.
https://github.com/FriendsOfREDAXO/mblock/commit/40d518c7857434093e74c6cc85b453e4a7127ec2
https://github.com/FriendsOfREDAXO/mblock/commit/4c349b7e2a9bedf383bafcbd4e64dd23c3ad7ad8

%%mb_count%% => <span class="mb_count">x</span>
%mb_count% => x

**Comment by phoebusryan** [comment]
Danke schön!

**Comment by joachimdoerr** [comment]
Muss großgeschrieben werden: 

%%MB_COUNT%% => <span class="mb_count">x</span>
%MB_COUNT% => x

**Comment by phoebusryan** [comment]
Naya, das wird dann zwar ersetzt, aber nicht hochgezählt. Sprich:

<legend>Mitarbeiter %%MB_COUNT%%</legend>

ist immer 1. auch wenn 10 vorhanden sind.

**Comment by joachimdoerr** [comment]
Das Problem kann ich nicht nachstellen.

**Comment by phoebusryan** [comment]
Lag an einem defekten JSON-String in der DB und wurde via PN in Slack gelöst.

**Comment by darwin26** [comment]
@phoebusryan ... wie wurde es gelöst?
Ich habe hier auch gerade das Problem das %%MB_COUNT%% ... schön hochzählt (+1).
Allerdings die einfache Variante %MB_COUNT%, nicht hochzählt. Wird auch scheinbar nicht beachtet, weil .find
`function mblock_set_count(element, item) {
    var countItem = item.next().find('span.mb_count'),`
bach dem span des Replacers sucht... oder?

**Comment by phoebusryan** [comment]
Hm stimmt. Wenn man %MB_COUNT% nutzt, zählt es nicht hoch bei neuen Blöcken. Bei %%MB_COUNT%% klappt es.

**Comment by darwin26** [comment]
evtl wäre es auch schön wenn der
<div class="sortitem"> eine ID des zählers $count (%%MB_COUNT%%) erhält.
srpich:
<div class="sortitem" id="mblock-item-1"> ... </div>
<div class="sortitem" id="mblock-item-2"> ... </div>

damit man diese einzelnen Blöcke ggf auch via JS direkt ansprechn könnte.
@Joachim was meinst?

**Comment by joachimdoerr** [comment]
Ich denke da eher an ein data-count statt id. das wäre schon gut als Ergänzung.

**Comment by darwin26** [comment]
jep. nehm ich gerne an ;)

**Comment by joachimdoerr** [comment]
data-unique="1"
data-unique-int="1"
set eine unique-id in das value - das ist doch schonmal was ;)
https://github.com/FriendsOfREDAXO/mblock/commit/ba6954dbc15f501e1c9ea3d67b247ae6eb2492e4

**Comment by eaCe** [comment]
Das funktioniert inzwischen, wenn das nicht der Fall ist, gerne wieder öffnen
