### ISSUE TITLE
In REX_INPUT_MEDIA und _LINK das INPUT entfernen

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mblock#23]
Das ist unschön und es wäre gut wenn es weg wäre. Das betrifft auch die Media- und Link-Listen.

**Comment by skerbis** [comment]
Was heißt das ganze für bestehende Module? Muss ich nur die Eingabe anpassen? Oder hat es auch Auswirkung auf die Ausgabe

**Comment by gut8er** [comment]
Ich steig hier leider auch noch nicht ganz durch ich habe in der eingabe MForm verwendet und in der Ausgabe <?php $image = rex_media::get($slide['REX_INPUT_MEDIA_1']); ?> und es funktioniert immernoch. Habe ich etwas überlesen oder falsch verstanden? Habe MBlock auf die aktuelle Version geupdated.
