### ISSUE TITLE
Ampersand (&) wird nicht mehr richtig ausgegeben

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/mblock#26]
Wenn man z.B. in ein Mblock-Feld Text a la 'Lorem & Ipsum' eingibt und speichert, landet es in der DB, wird aber nicht mehr korrekt ausgelesen.

**Comment by phoebusryan** [comment]
Ja das meine ich. In der DB ist es drin, ausgegeben wird es nicht.

**Comment by joachimdoerr** [comment]
Ist gefixt: https://github.com/FriendsOfREDAXO/mblock/commit/591ea1e16c3ea11968f198883fab3a6695604c34
NodeValue wird nicht überschrieben wenn ein & im string vorhanden ist, das problem trat nur bei textareas auf.
