### ISSUE TITLE
Bestehendes Modul via mblock erweitern

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#27]
Sollte ein bestehendes Modul via mblock erweitert werden, könnten die bisherigen Daten verloren gehen. 

Daher der Vorschlag, dass mblock vorher schaut, ob die Daten bereits in json vorliegen. Wenn nicht, konvertiert mblock die Daten und legt dies in das erste Feld.

**Comment by joachimdoerr** [comment]
Ja das kann man machen. Ist aber nicht grade wenig, da müsste ich mal schauen wie das am besten realisiert werden könnte. Das Problem ist ja auch die Modul-Ausgabe, diese müsste ja quasi das selbe berücksichtigen.

**Comment by joachimdoerr** [comment]
Ich denke MBlock sollte dafür nicht verantwortlich sein, ggf. könnte man ein Plugin konstruieren, welches das erledigen kann.

**Comment by tbaddade** [comment]
Ich hatte es damals in der Moduleingabe so gelöst:

```php
<?php
$data = json_decode('REX_VALUE[1]');
$json = (json_last_error() == JSON_ERROR_NONE) ? true : false;
$text = $json ? '' : 'REX_VALUE[1]';


// base ID
$id = 1;

$form = '
<fieldset class="form-horizontal">
    <div class="form-group">
        <div class="col-md-2 control-label"><label for="redactor_' . $id . '_0_text">Text</label></div>
        <div class="col-md-10">
            <textarea class="form-control redactorEditor2-standard" id="redactor_' . $id . '_0_text" name="REX_INPUT_VALUE[' . $id . '][0][text]" rows="10">' . $text . '</textarea>
        </div>
    </div>
</fieldset>';

// parse form
echo MBlock::show($id, $form);

**Comment by joachimdoerr** [comment]
Sollen wir das ein die Beispiele aufnehmen?

**Comment by tbaddade** [comment]
Ich schließe. Scheint nicht wirklich vorzukommen.
