### ISSUE TITLE
redactor2 nicht duplizierbar in mblock 1.6

### ISSUE THREAD

**Issue by ex-q** [FriendsOfREDAXO/mblock#29]
Sobald ein Block mit redactor2 in 1.6 dupliziert verschwinden alle redactor2 Instanzen. Bei 1.5 funktioniert es noch.

Lg, ex-q

**Comment by joachimdoerr** [comment]
ist jetzt in 1.6.2 gefixt.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/releases/tag/1.6.2

**Comment by darwin26** [comment]
Hallo @joachimdoerr ... 
hatte gerade Zeit zum testen. Leider läuft es noch nicht 100%ig rund (siehe video)
http://rexponsive.de/downs/mblock_redactor2_test.mp4

desweitern muss auch in redactor:
toolbarFixed: false (statt true)
gesetzt werden, sonst klebt sich die toolbar oben hin ;) ...

Danke. Gruß Chris

**Comment by joachimdoerr** [comment]
Da brauch ich mehr info: browser? Betriebssystem?

**Comment by darwin26** [comment]
OSX // FireFox 50.0.2 ...

**Comment by ex-q** [comment]
Mehrere Redacotrs anlegen klappt jetzt, vielen Dank dafür!

Der Bug von darwin26 tritt bei mir aber auch auf (Win 10 // Chrome 54).
Mehrere Blöcke anlegen/löschen versagt immer irgendwann mit 

`i18Uncaught TypeError: Cannot read property 'indexOf' of undefined
    at HTMLTextAreaElement.<anonymous> (https://example.com/assets/addons/mblock/mblock.js:267:42)
    at Function.each (https://example.com/assets/core/jquery.min.js:2:2861)
    at n.fn.init.each (https://example.com/assets/core/jquery.min.js:2:845)
    at HTMLDivElement.<anonymous> (https://example.com/assets/addons/mblock/mblock.js:266:38)
    at Function.each (https://example.com/assets/core/jquery.min.js:2:2861)
    at n.fn.init.each (https://example.com/assets/core/jquery.min.js:2:845)
    at mblock_reindex (https://example.com/assets/addons/mblock/mblock.js:258:28)
    at mblock_init_sort (https://example.com/assets/addons/mblock/mblock.js:62:5)
    at mblock_add_item (https://example.com/assets/addons/mblock/mblock.js:368:9)
    at HTMLButtonElement.<anonymous> (https://example.com/assets/addons/mblock/mblock.js:449:13)n`

**Comment by kobebeef** [comment]
Das erstellen von neuen Blöcken mit Redactor funktioniert bei mir (macOS / Safari 10).
Beim letzten hinzugefügten Block verliere ich aber beim Speichern den Inhalt.
Bei erneutem Editieren ist der Text weg. Füge ich dann Text ein und speichere, ist es ok.

**Comment by alfa-gonzalez** [comment]
Hallo @kobebeef 

War bei mir auch so..

Mit folgendem js-Fix funktionieren mehrere Redactors2 bei mir. Die Inhalte werden direkt nach dem Einfügen eines neuen Blocks gespeichert und gehen nicht verloren.  (getestet in Chrome)

redactor2 - v3.0.1
mblock - v1.6.2

In der Datei mblock.js (unter /assets/addons/mblock/), um Zeile 266..

Original:

```
$(this).find('textarea').each(function(){
    if ($(this).attr('class').indexOf("redactor") >= 0) {
        area = $(this).clone().css('display','block');
    }
});
```
Mit folgendem Code ersetzen:

```           
$(this).find('textarea').each(function(){
    var attr = $(this).attr('class');
    if (typeof attr !== typeof undefined && attr !== false) {
        if ($(this).attr('class').indexOf("redactor") >= 0) {
          area = $(this).clone().css('display','block');
        }
    }   
});
```

**Comment by joachimdoerr** [comment]
Thanks @alfa-gonzalez ! https://github.com/FriendsOfREDAXO/mblock/commit/0920f98c3c3df778be8783aa4574641f4680c759
