### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#31]
Bsp. Modul **Diverse Formularelemente** angelegt.
Im Slice Inhalte einfügen > speichern > wieder editieren

```
Warning: DOMElement::setAttribute(): ID already defined in /redaxo/src/addons/mblock/lib/classes/Decorator/MBlockFormItemDecorator.php on line 216
Warning: DOMDocument::importNode(): ID already defined in /redaxo/src/addons/mblock/vendors/phpQuery/phpQuery/DOMDocumentWrapper.php on line 462
```

**Comment by joachimdoerr** [comment]
Hab ich jetzt nicht nachstellen können. Gibts das Problem noch? Das Issue ist ja schon recht alt.

**Comment by joachimdoerr** [comment]
Mit der v1.7.2 hab ich das nicht nachstellen können.

**Comment by olien** [comment]
Mit mBlock 3.0 gibt es die Warning noch immer. mForm ist nicht installiert.

`Warning: DOMElement::setAttribute() expects exactly 2 parameters, 3 given in /Users/me/Sites/test/redaxo/src/addons/mblock/lib/MBlock/Decorator/MBlockFormItemDecorator.php on line 173`

**Comment by joachimdoerr** [comment]
Kann ich bitte den Modul Input haben so kann ich das nur schwer nachstellen.

**Comment by olien** [comment]
Ist etwas umfangreicher: https://github.com/FriendsOfREDAXO/bricky

**Comment by joachimdoerr** [comment]
hast du eine version online in der das vorkommt? so dass ich mir das mal dort anschauen kann?

**Comment by olien** [comment]
muß ich ml gucken evtl. heute abend...

hier ist es auch (Moduleingabe + Helper Class:





[Archiv.zip](https://github.com/FriendsOfREDAXO/mblock/files/2686588/Archiv.zip)

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/acecb6049149fed4f13f95581cf6dc4ac20b2077
