### ISSUE TITLE
REX_INPUT_VALUE wird nicht hochgezählt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#32]
beim hinzufügen eines weiteren Blocks bleibt `REX_INPUT_VALUE` gleich

Das initiale HTML sieht aktuell so aus

```html
<button type="button" class="btn btn-default iconpicker" name="REX_INPUT_VALUE[4][2][icon]" data-iconpickerset="fontawesome">
    <i class="fa fa-battery-full"></i>
    <input type="hidden" name="REX_INPUT_VALUE[4][2][icon]" value="fa-battery-full" />
    <span class="caret"></span>
</button>
```

Füge ich einen weiteren Block hinzu bleibt das `REX_INPUT_VALUE[4][2][icon]`unverändet im neuen Block.

**Comment by joachimdoerr** [comment]
Bei meinem Test wurde der Button nicht hochgezählt jedoch das Input Feld schon.

```
         <button type="button" class="btn btn-default iconpicker" name="REX_INPUT_VALUE[1][0][icon]" data-iconpickerset="fontawesome">
            <i class="fa fa-battery-full"></i>
            <input type="hidden" name="REX_INPUT_VALUE[1][1][icon]" value="fa-battery-full"><span class="caret"></span>
        </button>
```

Das liegt sicher daran, dass das Formular Feld "Button" in MBlock nicht berücksichtigt wird.

**Comment by joachimdoerr** [comment]
Das Problem müsste hiermit gefixt sein. https://github.com/FriendsOfREDAXO/mblock/commit/0f9aed0aa39b353ce2fa0e90d9b9f17f2be13f8f

**Comment by tbaddade** [comment]
> Das Problem müsste hiermit gefixt sein

Passt. Danke
