### ISSUE TITLE
reindex_end Event den hinzugefügten/gelöschten Block übergeben.

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#33]
Oder ein anderes Event erstellen, wenn das an der Stelle nicht sinnvoll ist.

Hintergrund,: Ich müsste einen Iconpicker neu initialisieren.

**Comment by joachimdoerr** [comment]
Macht schon sinn.

**Comment by ynamite** [comment]
Evtl. stehe ich gerade auf dem Schlauch, aber mittels ```mblock_module.registerCallback('reindex_end', functionblabla);```
kannst du doch dein eigene Callback Funktion definieren und tun und lassen was du möchtest?

**Comment by joachimdoerr** [comment]
Gelöst dank des Pullrequets von https://github.com/ynamite https://github.com/FriendsOfREDAXO/mblock/commit/9b6fa4a9092be8a639340b10981a56580b48ba9f Besten Dank dafür!

**Comment by tbaddade** [comment]
Hier hat sich hier in der Anwendung was geändert? Bisher funktionierte

```javascript
    if (typeof mblock_module !== 'undefined') {
        mblock_module.registerCallback('reindex_end', function() {
            IconpickerAddon.initMblock($('.mblock_wrapper'));
        });
    }
```

**Comment by tbaddade** [comment]
Das Problem von oben hat sich erledigt.
