### ISSUE TITLE
Fehler bei addRadioField #bug

### ISSUE THREAD

**Issue by shauste** [FriendsOfREDAXO/mblock#34]
Ich binde zwei Radiofelder ein:
`$mform->addRadioField("$id.0.placement",array('left'=>'linke Spalte','right'=>'rechte Spalte'),array('label'=>'Platzierung'));`

Wählt man nach Einsetzen des 1. Moduls das 1. Radiofeld aus und fügt einen weiteren Mblock (+) hinzu, verliert das 1. Radioset im 1. MBlock den Wert.

**Comment by shauste** [comment]
Tests haben gezeigt, dass der Wert des for-Attribut nicht korrekt ausgegeben wird. Hier fehlt der Zähler. Beispiel: `for="rv7_1_0_placement2"` statt `for="rv7_1_1_placement2"` beim 2. mblock.

**Comment by shauste** [comment]
Entferne ich die Kommentare der Zeilen 151 - 153 funktioniert der Zähler auch im for-Attribut:
https://github.com/FriendsOfREDAXO/mblock/blob/master/assets/mblock.js#L151-L153

**Comment by shauste** [comment]
Konnte es gerade im Livesystem testen, klappt leider doch nicht.

**Comment by joachimdoerr** [comment]
Ja der Radiobutton funktioniert noch nicht. Hier empfiehlt es sich auf ein Select zurück zu greifen. Das Problem mit den Radiobuttons hat was mit dem PHP Part von MBlock zu tun. Das Javascript ist hier das kleinere Problem.

**Comment by shauste** [comment]
Danke für die Rückmeldung.
Verstehe ich nicht ganz; Wenn im Block bereits mehrere MBlöcke mit radio-Boxen existieren, werden die Werte korrekt gesetzt, wenn ich den Block editiere. Der Fehler tritt nur im Zusammenspiel beim Hinzufügen eines neuen Mblocks auf.

**Comment by joachimdoerr** [comment]
Ich muss mir das Problem nochmals anschauen. Ggf. finde ich eine "leichte" Lösung dafür.

**Comment by joachimdoerr** [comment]
Das Problem sit nun behoben der fix läuft dann in den nächsten release: https://github.com/FriendsOfREDAXO/mblock/commit/98e5f93783b3b63b7ec63434a5140ebdce2e1e41
