### ISSUE TITLE
Bei Installation mblock dependencies prüfen

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mblock#35]
Falls noch unbekannt: hab gerade zum ersten mal mblock installiert und wollte ein Test-Modul einsetzen, dabei erhielt ich die Fehlermeldung`class mform not found`

Wäre top wenn das Addon bei der Installation prüft ob mform vorhanden ist.

Edit: aber ansonsten feine Sache! :)

**Comment by skerbis** [comment]
Hallo @ynamite mblock setzt mform nicht voraus. Die Addons ergänzen sich können aber unabhängig funktionieren. Du kannst für mblock auch klassische Module schreiben und diese duplizieren. Wenn du Deine Module mit mform schreiben möchtest, musst du mform auch installieren.

**Comment by ynamite** [comment]
Ah Mist, hatte ich gestern nicht geschnallt. Würde es dann aber nicht mehr Sinn machen, bei den Beispielen ohne mform zu arbeiten?

**Comment by tbaddade** [comment]
>  bei den Beispielen ohne mform zu arbeiten?

Da gibt es Beispiele ohne `mform`.

**Comment by skerbis** [comment]
Die Prüfung ob mform installiert ist könnte im Manual stattfinden. Mblock könnte dann für die Verwendung der mblock-Beispiele die Installation von mform empfehlen, wenn es nicht installiert ist.

**Comment by tbaddade** [comment]
> Mblock könnte dann für die Verwendung der mblock-Beispiele die Installation von mform empfehlen, wenn es nicht installiert ist.

Oder die Beispiel, die mform benötigen, erst gar nicht anzeigen.

**Comment by ynamite** [comment]
@tbaddade Ah OK. Hatte einfach das erste Beispiel ausprobiert und nicht genauer geschaut. Mein Fehler ;)

**Comment by joachimdoerr** [comment]
Ich sehe da kein Grund die Beispiele zu entfernen. Man könnte aber einen Hinweis platzieren sollte MForm nicht installiert sein.

**Comment by ynamite** [comment]
Hab mich inzwischen eingearbeitet, super Sache! Bin echt begeistert!

Ich denke die Beispiele sind völlig in Ordnung. Wer sich, nicht so wie ich, die Zeit nimmt zu lesen was auf der Seite mit den Beispielen steht, dürfte keine Probleme haben ;)

Evtl. könnte man sich überlegen die HTML-Beispiele initial zu zeigen, statt den MForm Beispiele. 

Jedenfalls war das ganz klar mein Versäumnis!

**Comment by joachimdoerr** [comment]
closed
