### ISSUE TITLE
Alternative REX_VARs funktionieren nicht

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#37]
Bsp.
`REX_YFORM_TABLE_DATA[id=1 output="widget" table="yform_table" field="name"]`

Wird zwar korrekt angezeigt, aber die Daten werden nicht richtig gespeichert bzw. gelesen.

**Comment by joachimdoerr** [comment]
Gespeichert werden die Daten sicher, aber gelesen nicht da MForm direkt aus dem Slice Datensatz die Values ausliest und in das Formular schreibt.

**Comment by joachimdoerr** [comment]
Wie genau funktionieren diese Felder? Werden die speziell von YForm versorgt?

**Comment by tbaddade** [comment]
> Wie genau funktionieren diese Felder?

wie `REX_LINK, REX_LINKLIST, REX_MEDIA, REX_MEDIALIST` nur eben mit eigenen Params

**Comment by joachimdoerr** [comment]
Wird das auch im Slice gespeichert? oder sonstwo? 

Ein Modul Beispiel wäre super.

**Comment by joachimdoerr** [comment]
Mit dem widget kann man die Wert von Haus aus nicht in ein rex_json speichern.
Das Widget ist somit das Problem bei der ganzen Sache. Es erzeugt ein hidden Input-field welches den Wert als REX_INPUT_VALUE abspeichern, das macht das ganze etwas schwieriger.

**Comment by tbaddade** [comment]
Inwiefern ist das Widget das Problem. Die REX_MEDIA / LINK Widgets verwenden doch auch `hidden` Felder.

Müsste man nicht nur `REX_INPUT_VALUE` anpassen sobald as ein `REX_VAR`.
Also aus `REX_INPUT_VALUE` wird wie bei `REX_LINK` dann 
`REX_INPUT_VALUE[4][0][REX_INPUT_YFORM_TABLE_DATA_1]`

**Comment by joachimdoerr** [comment]
Das stimmt doch die Link und Media Widgets wollen aus der DB Link oder Media Columns auslesen und schreiben dann nichts in den Value, das ist beim Tabellen Widget anders das schreibt den JSON-String in das Value was das HTML zerstört wegen der Anführungszeichen. Ich hab schon begonnen mit dem Umschreiben des Name-Attributes - läuft soweit aber eben beim nachträglichen Editieren gibts Probleme.

**Comment by tbaddade** [comment]
@joachimdoerr Kannst du sagen, wann MBlock alternative Widgets unterstützen wird?

**Comment by joachimdoerr** [comment]
Momentan hab ich keine Idee wie ich das umsetzen kann. Das Problem sind die Widgets welche den gesamten String in das Value schreiben. Da das ein kompletter JSON-String ist zerhaut es das HTML so hart, dass ich da nichts mehr machen kann.

**Comment by joachimdoerr** [comment]
Das wird nur in Zusammenhang mit mform funktionieren können da die widgets an sich die den gesamten rex_value in das value des input Feldes schreien, das zerschießt dann das html und ich kann via DOMDocument nichts mehr manipulieren. Mit MForm könnte man die Widgets ähnlich wie die MediaButtons initialisieren und dieses verhalten unterdrücken.

**Comment by tbaddade** [comment]
> Das wird nur in Zusammenhang mit mform funktionieren können da die widgets an sich die den gesamten rex_value in das value des input Feldes schreien,

Ich fände es besser, wenn es komplett ohne MForm funktionieren könnte. Wenn die alternativen Widgets in eine eigene Column schreiben würden, dann wäre es einfacher?

**Comment by joachimdoerr** [comment]
Ja es wäre wesentlich einfacher bzw. der einzige weg aus meiner Sicht.

**Comment by tbaddade** [comment]
Problem scheint immer noch vorhanden zu sein, eine Lösung aber nicht in Sicht bzw. schwer umzusetzen. Daher schließe ich.

Wenn jemand @joachimdoerr hier unterstützen mag, gern wieder öffnen.

**Comment by tbaddade** [comment]
Ich bin wieder an der Stelle, dass ich ein eigenes REX_VAR in MBLock nutzen möchte.

> Das stimmt doch die Link und Media Widgets wollen aus der DB Link oder Media Columns auslesen und schreiben dann nichts in den Value, das ist beim Tabellen Widget anders das schreibt den JSON-String in das Value was das HTML zerstört wegen der Anführungszeichen. 

Warum schreiben REX_LINK und REX_MEDIA nicht in die eigenen Felder? Das wird scheinbar auch unterbunden. Wo muss man ansetzen, damit eigene Values funktionieren? Vielleicht kannst du auch noch einmal das Problem genauer erläutern. Ich wäre sehr an eine Lösung für MBlock interessiert

**Comment by joachimdoerr** [comment]
@tbaddade  rex_link und rex_media können nicht in die eigenen vars notieren, das widerspricht dem Grundprinzip von MBlock. 

RexVars:
- Die Inhalte von vielen Blöcken werden als JSON in ein RexVar notiert. 
- Anhand des JSON erkennt MBlock dann was in die einzelnen Blöcke geparst werden muss. 
- Beim Editieren parst dann der PHP Part von MBlock das Form X mal anhand dieses JSON.
- Während des Bearbeitens kümmert sich das JS darum, dass die Blöcke verschoben, entfernt, dupliziert oder neu angelegt werden können.

Das Problem mit YForm-Widgets:
- Da RexLink, RexLinklist, RexMedia und RexMedialist ihre eigenen Var beschreiben wollen die Widgets auch aus den "eigenen" Var initial auslesen -> das kommt MBlock nicht in die quere da es dort jeweils simple Springs ausliest und diese in das Form Element Printer (vordem MBlock versucht irgendetwas zu manipulieren). 
- Bei dem YForm-Widget ist das etwas anders diese lesen RexVars aus.
- Sofern dann in diesen das gesamt JSON von MBlock steht kommt es zum HTML Desaster da das Widget stumpf den RexVar Inhalte in das Form Element printed.
- Jetzt versucht MBlock nachträglich das HTML via DOMDocument/DOMElement zu manipulieren jedoch ist jetzt im HTML der gesamte JSON String mit allen " Anführungszeichen in das Value- und Name-Attribute vom YForm Widget HTML Element geschrieben was das HTML zerstört und es MBlock nicht ermöglicht dieses zu Manipulieren. 

Lösung: 
- Bester Weg wäre, wenn das Widget den Inhalt aus seinem RexVar nicht auslesen würde, man müsste irgendwie beim initialisieren diese Mechanik via Parameter unterdrücken können.
- Andere Lösung man string replaced den JSON String aus dem HTML Formular String bevor dieser als DOMDocument eingelesen wird.
