### ISSUE TITLE
CKEditor compat

### ISSUE THREAD

**Issue by RexDude** [FriendsOfREDAXO/mblock#38]
Hi!
der Ck weisst die gleichen Freezes auf wie anscheind die anderen Editoren zuvor. Wie habt ihr dass Problem gefixt? Kann hier jemand behilflich sein? Aktuelle Version hier: https://github.com/RexDude/ckeditor
P.s: sowohl beim Block anlegen als auch beim Hoch/runter schieben hängt er fest.

**Comment by skerbis** [comment]
@joachimdoerr Kannst Du helfen?

**Comment by joachimdoerr** [comment]
Ja ich muss mir das mal in Kombi anschauen. Das ist natürlich immer recht schwierig mit den Editoren. MBlock dupliziert ja das HTML eines Blockes sobald man auf "+" klickt. Danach müssen dann die darin eingesetzten Javascripts reinitialisiert werden. Da haben wir dann aber schnell das Problem das die bereits vorhandenen Editor Felder Fehler werfen und es zu unschönen Seiten Effekten kommt hier beginnt dann der Wahnsinn... Deswegen kann man das nicht so einfach Pauschal regeln.

**Comment by RexDude** [comment]
Ja das hab ich fast befürchtet. Du hast da ja auch jede Menge extra Code zu den anderen Editoren drin. Ich glaube dass Grundproblem ist dass Mblock den gesamten DOM dupliziert (wenn ich dass richtig verstanden habe). Damit wird auch ein bereits initialisierter Editor dupliziert was die wohl nicht verkraften. Hier als mal eine Idee: nur den reinen HtmlCode duplizeren (also die textarea mit den klassen) und dann einen event bereitstellen wo die editoren drauf reagieren können und die neue textarea mit einer neuen Editor Instanz intialisieren. Theoretisch... ;)

**Comment by joachimdoerr** [comment]
Ich habe ein aktiven Support nur für redactor und markitup. Für das TinyMCE Addon wurden Events eingezogen. Das Item wird geklont, da könnte man sicher noch dran drehen.

https://github.com/FriendsOfREDAXO/mblock/blob/master/assets/mblock.js#L344

**Comment by joachimdoerr** [comment]
Wie haben im Ticket auf Seiten CKEditor Lösungswege besprochen - es wird sich eher auf dieser als auf der MBlock Seite eine Lösung finden lassen. https://github.com/RexDude/ckeditor/issues/29 
Mit Sicherheit werden die MBlock Events dazu beitragen können, dass der CKEditor dann läuft.
