### ISSUE TITLE
MultiSelect speichert nicht

### ISSUE THREAD

**Issue by MarshallGibson** [FriendsOfREDAXO/mblock#41]
Hab gesehen, dass dies bereits gefixt sein sollte, aber Multiselect-Felder lassen sich nicht mehr bearbeiten.

Beim Hinzufügen des Blocks werden die Daten zwar gespeichert, aber nach dem Bearbeiten übernimmt es die neuen Werte nicht.

**Comment by joachimdoerr** [comment]
Nutzt du MForm? Hast du ein Beispiel Modul-Input damit ich das mal nachstellen kann.

**Comment by MarshallGibson** [comment]
Ja in Kombination mit mform.

Müsste es wieder nachbauen, hab kurzer Hand eine Zwischenlösung finden müssen. 

Ich schick es dir morgen. 

Lg, Thomas 
-- 
Diese Nachricht wurde von meinem Android Mobiltelefon mit GMX Mail gesendet.Am 26.02.17, 14:48, "Joachim Dörr" <notifications@github.com> schrieb:

  
    
      Nutzt du MForm? Hast du ein Beispiel Modul-Input damit ich das mal nachstellen kann.

**Comment by joachimdoerr** [comment]
Leider konnte ich das nicht nachstellen. Ggf. müsstest du die neusten MForm laden und deinen Browser-Cache leeren um zu gewährleisten, dass das Javascript auch überschrieben wird. Ab MForm 5.3 wird das automatisch ohne cache leeren passieren. 

Ich habe mit folgendem Modul getestet und konnte keinen Fehler feststellen.
Input:
```php
<?php

// init mform
$mform = new MForm();

// fieldset
$mform->addFieldset('Select elements');
// select
$mform->addSelectField("1.0.1", array(1=>'test-1',2=>'test-2',3=>'test-3',4=>'test-4'), array('label'=>'Select optgroup'));
// select optgroup
$mform->addSelectField("1.0.2", array('group 1'=>array(1=>'test-1',2=>'test-2'), 'group 2'=>array(3=>'test-3',4=>'test-4')), array('label'=>'Select optgroup'));
// fieldset
$mform->addFieldset('Multiselect elements');
// multiselect
$mform->addMultiSelectField("1.0.3", array(1=>'test-1',2=>'test-2',3=>'test-3',4=>'test-4'), array('label'=>'Select optgroup'));
// multiselect optgroup
$mform->addMultiSelectField("1.0.4", array('group 1'=>array(1=>'test-1',2=>'test-2'), 'group 2'=>array(3=>'test-3',4=>'test-4')), array('label'=>'Select optgroup'));
// parse form
echo MBlock::show(1, $mform->show());
?>
```
Output: 
```php
<?php

echo '<pre>';
print_r(rex_var::toArray("REX_VALUE[1]"));
echo '</pre>';

?>
```

Kannst du mit dem Modul ein Test durchführen und bestätigen ob alles läuft?

**Comment by joachimdoerr** [comment]
Tatsächlich konnte ich das jetzt nachstellen, das Problem taucht nur mit MForm Modulen auf. Ich habe das bereits in MForm gefixt, dort wird das dann mit den nächsten Release publiziert. 

https://github.com/FriendsOfREDAXO/mform/commit/1e4b74f835a45ea1546b4f24504744a8039841be
