### ISSUE TITLE
reindex_end : Element ist undefined

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#43]
ob beim hinzufügen oder löschen eines Blocks: `item` ist aktuell in der 1.7.1 immer `undefined`

```
mblock_module.registerCallback('reindex_end', function( item ){
    console.log(item);
});
```

ping @ynamite

**Comment by ynamite** [comment]
Die fixes sind noch nicht im installer, wie's scheint.

**Comment by joachimdoerr** [comment]
stimmt.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/releases/tag/1.7.2
