### ISSUE TITLE
Wenn `min=1` und `max=1` Icons ausblenden

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#45]
Icons add und delete könnten ausgeblendet werden, wenn

`MBlock::show($id, $form, ['min' => 1, 'max' => 1]);`

notiert wird.

**Comment by darwin26** [comment]
dann bräuchte man aber auch nicht wirklich mblock dafür... oder warum legt man extra n mblock mit min1 max1 an... *graddrübernachdenk*

**Comment by skerbis** [comment]
@darwin26 So muss man ein Modul nur einmal programmieren. Evtl. benötigt man es in einem anderen Projekt nur als Einzel-Modul, ist aber so frei, es umzustellen.

**Comment by tbaddade** [comment]
> oder warum legt man extra n mblock mit min1 max1 an

Hie im konkreten Fall ist es so, dass der Kopfbereich der Seite ein Bild in voller Breiter bekommt. Aktuell ist laut Design kein Slider vorgesehen, kann so aber recht schnell integriert werden und der Kunde muss nicht alle Blöcke neu anlegen bzw. bearbeiten. Nur eben die, wo ein Slider erscheinen soll.

**Comment by darwin26** [comment]
hmm.. ich mach das von vornherein... und prüfe ab ob er nur 1 gefüllt hat...
wenn größer 1 = mach slider... quasi 2 in einem 😊. . .

**Comment by joachimdoerr** [comment]
Schon cool was ihr da alles mit MBlock baut! Als workaround kannst du das mit JS ja rausputzen. Da der Setting min und max als data im MBlock Wrapper platziert wird.

**Comment by skerbis** [comment]
Thomas und Thomas hätten gerne eine Lösung in der  man den Slider leicht als Upgrade verkaufen kann ;-)

**Comment by tbaddade** [comment]
@darwin das macht das Modul, nur kann der Redakteur aktuell nur einen Block pflegen. Er möchte irgendwann einen Slider? max=5 fertig. Wie @skerbis schon schrieb.

@joachimdoerr ich fände es gut, wenn das mblock von sich aus könnte.

**Comment by olien** [comment]
Sinnvoll wäre es ja auch die hoch/runter sowie den Anfasser zum verschieben auszublenden - oder?

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/82e4dc581f3a1822e20b9cb7830758bbfe96f271
