### ISSUE TITLE
Bitte redactor2-Einbindung ermöglichen. 

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mblock#5]
sorgt leider noch für Probleme: Bei aktiviertem Redactor, crasht das Javascript

**Comment by joachimdoerr** [comment]
Crasht - was passiert genau?

**Comment by skerbis** [comment]
Drag & Drop und löschen geht nach dem duplizieren nicht.

**Comment by joachimdoerr** [comment]
done. https://github.com/FriendsOfREDAXO/mblock/commit/59a78e8938374d026fcbb495ab5d1a8ae11e6390
