### ISSUE TITLE
Prüfen ob php-xml installiert ist

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#50]

**Comment by joachimdoerr** [comment]
Beim installieren von MBlock, oder generell?

**Comment by tbaddade** [comment]
> Beim installieren von MBlock, oder generell?

Wie generell? Am besten in die package.yml bei requires notieren.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/6c00bb268227c2e255dc780770da18da069069ea
