### ISSUE TITLE
Mblock für Metainfos

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#52]
Idee: Metainfofelder gruppieren und als Mblock ausgeben

**Comment by joachimdoerr** [comment]
Gefällt mir! Ich muss mal prüfen wie sich das in den Metaformularen platzieren lässt.

**Comment by tbaddade** [comment]
@joachimdoerr Falls du hier keinen Bedarf mehr siehst gerne schließen.
