### ISSUE TITLE
Drag&Drop: Value Radiobutton geht verloren

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/mblock#54]
Kleines, aber blödes Problem beim Rumspielen mit mblock festgestellt.
Zum Reproduzieren folgendes Input-Modul benutzen:

```
<?php
### interne ID
$id = 1;

### Formular erstellen
$form = new MForm();

### Fieldset erstellen (wird automatisch geschlossen!)
$form->addFieldset('Element');

### Slide: Box-Ausrichtung
$form->addRadioField("$id.0.ausrichtung");
$form->setOptions([0 => 'links', 1 => 'zentriert', 2 => 'rechts']);
$form->setAttributes(array(
	'label'=>'Box-Ausrichtung'
));

### MBlock-Formular parsen
echo MBlock::show($id, $form->show(), array('min'=>1,'max'=>4));
?>
```

Auf meinem Redaxo 5.3. erstelle ich einen neuen Slice mit diesem Modul und gebe beiden Radiobuttons einen Wert. Dann speichern. Jetzt direkt wieder editieren und mit Drag&Drop die Anordnung der "mblocks" verändern => Dabei geht mir immer ein Value flöten und ich muss den verloren gegangenen Radiobutton neu setzen.

Da man hier in eine böse Ausgabefehler-Falle tappen kann (wenn keine Validierung erfolgt) wäre es hilfreich, wenn sich das mal jemand anguckt, der sich damit auskennt :)

Vielen Dank und Grüße
dpf.dd

**Comment by joachimdoerr** [comment]
Das Problem besteht nicht mehr mit der neusten MForm und MBlock Version.
