### ISSUE TITLE
Einzelne Blöcke analog zu Accordioneffekt ermöglichen

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#55]
Könnte ggf. so funktionieren, wenn MB_COUNT kein HTML liefern würde

```html
<div class="panel panel-default">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a data-toggle="collapse" href="#collapse-%%MB_COUNT%%">Bild %%MB_COUNT%%</a>
        </h4>
    </div>
    <div class="panel-body" id="collapse-%%MB_COUNT%%">
        ...
    </div>
</div>
```

**Comment by joachimdoerr** [comment]
%MB_COUNT% liefert nur den count jedoch nur ausgehend vom php also int Zahlenwerte im html
%%MB_COUNT%% liefert hingegen html damit das via Javascript erkannt und weiter gecountet werden kann.

**Comment by joachimdoerr** [comment]
Ich schließe mal da %MB_COUNT% das beschriebene Problem entsprechend löst.
