### ISSUE TITLE
Unterstützung für yForm-Tools

### ISSUE THREAD

**Issue by phoebusryan** [FriendsOfREDAXO/mblock#56]
Ich nutze immer wieder mal die yForm-Tools (z.B. den Datepicker), welche mit mblock nicht kompatibel sind. Sprich, wenn man einem Inputfeld z.B. das Attribut 'data-yform-tools-datepicker="YYYY-MM-DD"' gibt, funktioniert es für die bestehenden aber nicht für neue Blöcke. Wäre schön, wenn man das fixen könnte :)

**Comment by joachimdoerr** [comment]
Das ist wieder die Grundsatz frage ob MBlock jedes Javascript unterstützen sollte das durch verschiedene Addons geliefert wird. Bis jetzt war die Entscheidung hier eher das nicht zu tun und entsprechende Javascript Events anzubieten auf die man reagieren kann um Javascript dann reinitialisieren zu können für die neu erstellen MBlock-Elemente.

**Comment by phoebusryan** [comment]
Grundsätzlich sinnvoll. Dann müssten man einfach die Events abgreifen können m.

**Comment by joachimdoerr** [comment]
closed weil Duplikat: https://github.com/FriendsOfREDAXO/mblock/issues/37
