### ISSUE TITLE
default-values nur beim ersten Element

### ISSUE THREAD

**Issue by dpf-dd** [FriendsOfREDAXO/mblock#58]
Moin,

habe gerade folgendes Problem festgestellt, evtl. kann das ja jemand bestätigen und ggf. sogar fixen :D 

**Modul-Input**

```$form->addTextField("$id.0.textfeld");
$form->setAttributes(array(
	'label'=>'Textfeld',
	'style'=>'width: 100%',
	'default-value'=>'blablablubb'
));
```
Der  default-value "blablablubb" steht nur im ersten Element. Jedes weitere neu hinzuzufügende Element besitzt keinen voreingestellten default-value mehr. Dieses Verhalten konnte ich auch bei Select-Feldern beobachten...

Ist jetzt kein großes Ding, geht natürlich auch erstmal ohne. Aber falls das noch nicht bekannt ist melde ich es mal. Sieht für mich wie ein kleiner Bug aus...

Danke und viele Grüße
dpf-dd

**Comment by joachimdoerr** [comment]
Das liegt am Javascript von MBlock welches die Formular-Felder bereinigt. Der Default-Value wird dadurch auch entfernt.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/issues/82
