### ISSUE TITLE
Drag & Drop für Fieldsets innerhalb eines Datenblocks

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#59]
Hi Joachim,

ich schreibe gerade viele Moduel und wenn ich innerhalb eine Datenblocks die Fieldset Reihenfolge ändern könnte (Ausgabe müsste selbstverständlich berücksichtigt werden) wäre das ein großer Meilenstein.

Ist so etwas realisierbar?

LG
Oliver

**Comment by joachimdoerr** [comment]
Das wäre ja quasi ein nestes MBlock, das ist so ohne weiteres nicht möglich.

**Comment by joachimdoerr** [comment]
Ich schließe mal nested MBlocks nicht vorgesehen sind und ich denke nicht, dass es einfach möglich ist diese in MBlock einzuziehen. Gerne wieder öffnen sollte ich das falsch verstanden haben.
