### ISSUE TITLE
Mehre MBLOCK - Abschnitte in einem Block ermöglichen

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mblock#6]

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/4a59d9341a0808e9bf678a02c7189704c1a6f61a
https://github.com/FriendsOfREDAXO/mblock/commit/c719365c1a81336e7a4ae7e489e40598576e4cb5
