### ISSUE TITLE
array('min'=>1,'max'=>1) - Hört sich doof an - was? :-)

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#60]
Hallo Joachim,

ich mag es wenn alles mehr oder weniger gleich aussieht. Wenn ich alle meine Module mit mform / mblock baue soll alles möglichst gleich aussehen. 

Das heisst aber auch, dass ich für einen Datenblock der nicht dupliziert werden können soll auch mblock nutze. Hier wäre es schön, wenn dann die Navi rechts oben (Plus, Trash, Up, Down) und der Anfasser links nicht dargestellt werden würden.

Wie denkst Du darüber?

LG
Oliver

**Comment by IngoWinter** [comment]
https://github.com/FriendsOfREDAXO/mblock/issues/45 ;)

**Comment by olien** [comment]
Ups. Kann dann ja hier geschlossen werden :-)
(Danke)
