### ISSUE TITLE
mblock-array wird eindimensional zurückgegeben, wenn nur ein Item

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mblock#61]
statt
```
$var[0]['name']
$var[0]['description']
$var[0]['foo']
```
ist die Struktur dann
```
$var['name']
$var['description']
$var['foo']
```

Das ist ungünstig, weil man so nicht mehr einfach mit foreach durchgehen kann.

**Comment by joachimdoerr** [comment]
hast du ein Modul input bei dem das vorkommt ich kann das nicht nachvollziehen

**Comment by joachimdoerr** [comment]
Ich hab es erneut versucht kann das problem nicht nachstellen.

**Comment by alexplusde** [comment]
Kann das jetzt auch nicht nachprüfen, vlt war es ein anderer Fehler

**Comment by joachimdoerr** [comment]
ist ja schon alt ggf. betraf es eine alte version.
