### ISSUE TITLE
den Block einen Status anheften

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#63]
Ähnlich dem SliceStatus könnte man vorübergehend einen Block "offline" nehmen.

**Comment by joachimdoerr** [comment]
Ja könne man machen gerne per PR, du bist ja auch fit mit JS und PHP ;)

**Comment by joachimdoerr** [comment]
Also Status ist möglich das Problem ist aber, dieser wäre nicht unabhängig von der Ausgabe -> da diese ja nicht über MBlock läuft sondern direkt aus rex_var::toArray(REX_VALUE[x]); kommt, müsste man dann selbst dafür sorgen, dass dieser im output je nach dem berücksichtigt wird. Was möglich wäre, wäre dieser methode ein Event also Extensionpoint zu verpassen das MBlock dann nutzen könnte.

**Comment by joachimdoerr** [comment]
@tbaddade Vorschläge?

**Comment by tbaddade** [comment]
@joachimdoerr In der Ausgabe das Value nicht via `rex_var::toArray` nutzen sondern eventuell so etwas in der Art.

```
$blocks = MBlock::parse('REX_VALUE[1]');
foreach ($blocks as $block) {
    if ($block->isOnline()) {
        echo $block->getValue('heading');
    }
}
```

**Comment by joachimdoerr** [comment]
Ich würde wenn dann eher so etwas machen wollen `mblock_rex_var::toArray` hat der block dann ein mblock_status 0 wird er nicht mit ausgeliefert.

**Comment by tbaddade** [comment]
> wird er nicht mit ausgeliefert.

ich fände es gut, wenn du dich hier am Core orientierst. Normal werden alle geliefert, über einen Parameter nur die die online sind.

**Comment by tbaddade** [comment]
Genau, wobei ich den Methodennamen ändern würde.
