### ISSUE TITLE
move Buttons nicht korrekt

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#64]
Schiebt man einen Block an erster Stelle, ist der moveUp Button noch aktiv und der moveDown Button inaktiv. Man kann den jetzigen ersten Block nicht mehr nach untern schieben.

Beim letzten Block ist ebenso das falsche in/aktive Verhalten zu sehen.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/025fd2572b6db6777960d15c5163659a9436acd1
