### ISSUE TITLE
addSelectField aus der Beispiel-Sammlung funzt nicht

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mblock#66]
@joachimdoerr Betrifft aktuelle mblock/mform Kombination.

```
$id = 1;

$mform->addSelectField("$id.0.test4", array(1=>'test-1',2=>'test-2',3=>'test-3',4=>'test-4'), array('label'=>'Select'));

echo MBlock::show($id, $mform->show(), array('min'=>1)); // add settings min and max

```

Ist direkt aus der Beispielsammlung und führt bei mir zur Fehlermeldung: 

```
Argument 2 passed to MBlockFormItemDecorator::replaceOptionSelect() must be an instance of DOMElement, instance of DOMText given, called in /home/***/www/***/redaxo/src/addons/mblock/lib/classes/Decorator/MBlockFormItemDecorator.php on line 78 and defined
```

Scheinbar hat sich bei Select-Felder etwas geändert. Nur was? Finde keine Info dazu.

**Comment by joachimdoerr** [comment]
Hast Du ein MForm update durchgeführt? Nachträglich, nach dem schon zuvor Inhalte erfasst wurden?
Siehe: https://github.com/FriendsOfREDAXO/mform/blob/master/CHANGELOG.md#version-510

**Comment by ynamite** [comment]
@joachimdoerr 
Ja, alles ist aktuell.

Ist zwar in dem Fall richtig, dass das Update nachträglich stattfand, aber selbst wenn ich nun einen ganz neuen Block einfüge, erhalten ich bei erneutem Editieren diesen Fehler. 

Scheint also nicht damit zusammenzuhängen dass Inhalte bereits vorhanden sind.

**Comment by kobebeef** [comment]
Ich habe das selbe Problem. Ist da irgendeine Lösung in Sicht?

**Comment by ynamite** [comment]
@kobebeef 
siehe mein PR/Commit: https://github.com/FriendsOfREDAXO/mblock/blob/master/lib/classes/Decorator/MBlockFormItemDecorator.php#L78-L81

**Comment by kobebeef** [comment]
uff… danke!

> Am 26.01.2018 um 14:17 schrieb Yves Torres <notifications@github.com>:
> 
> @kobebeef
> siehe mein PR/Commit: https://github.com/FriendsOfREDAXO/mblock/blob/master/lib/classes/Decorator/MBlockFormItemDecorator.php#L78-L81
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 



* * * * *
Neue Projekte:
https://www.arcas-foundation.ch
https://www.luftseilbahnglueck.ch

* * * * *

KOBEBEEF / Marc Rinderknecht, Webdesign & Development
Feldgütliweg 2, 8004 Zürich
+41 43 343 96 62 / +41 79 610 17 27
https://www.kobebeef.ch
https://www.facebook.com/kobebeef.ch/

* * * * *

Täglich ausser Mittwoch im Büro erreichbar.

**Comment by joachimdoerr** [comment]
@ynamite und @kobebeef könnt ihr verifizieren das es mit dem PR läuft? Dann bitte das Issue schließen. Und: Danke für Euren Einsatz!

**Comment by kobebeef** [comment]
Ja, es läuft. Selectgroup muss man aber noch anschauen.
Dank geht an @ynamite für den Fix.

> @ynamite und @kobebeef könnt ihr verifizieren das es mit dem PR läuft? Dann bitte das Issue schließen. Und: Danke für Euren Einsatz!



* * * * *
Neue Projekte:
https://www.arcas-foundation.ch
https://www.luftseilbahnglueck.ch

* * * * *

KOBEBEEF / Marc Rinderknecht, Webdesign & Development
Feldgütliweg 2, 8004 Zürich
+41 43 343 96 62 / +41 79 610 17 27
https://www.kobebeef.ch
https://www.facebook.com/kobebeef.ch/

* * * * *

Täglich ausser Mittwoch im Büro erreichbar.

**Comment by ynamite** [comment]
@joachimdoerr hab's nicht ausgiebig getestet, war nur ein akuter Fix für eine bestehende Website :)

**Comment by joachimdoerr** [comment]
ok da fehlt halt die instanzierung von mform

```$mform = new MForm();```

**Comment by ynamite** [comment]
Wie meinst du das? In meinem Beispiel?

**Comment by joachimdoerr** [comment]
ja das ist mir aufgefallen an dem Beispiel jedenfalls lässt sich der fehler nicht mehr nachstellen wenn man mform instanziert, der bugfix greift also

**Comment by ynamite** [comment]
Ah OK, alles gut! :)

**Comment by eaCe** [comment]
Hey, kann es sein das es generell Probleme mit Selects gibt? Immer wenn ich eins einfüge knallt es :(

Der Quick wirft eine notice:
Notice: Undefined property: DOMText::$tagName in D:\yakamara\raumwerk\src\addons\mblock\lib\classes\Decorator\MBlockFormItemDecorator.php on line 78

Ohne default angaben funktioniert es ohne eine solche

**Comment by eaCe** [comment]
Ich habe nun mal ein update zu meinem Fall:

Zuerst habe ich das debugging von phpQuery eingeschaltet. Dabei gab es einen Fehler hier:
https://github.com/FriendsOfREDAXO/mblock/blob/master/vendors/phpQuery/phpQuery/phpQueryObject.php#L3112

Dort habe ich dann `split()` durch`explode()` ersetzt.
Und in `MblockFormItemDecorator.php` :

```
if ($matches = $document->find('select'))
        {
            /** @var DOMElement $match */
            foreach ($matches as $match)
            {
                // continue by media elements
                if (strpos($match->getAttribute('id'), 'REX_MEDIA') !== false
                        or strpos($match->getAttribute('id'), 'REX_LINK') !== false)
                {
                    continue;
                }
                // label for and id change
                self::replaceForId($document, $match, $item);
                // replace attribute id
                self::replaceName($match, $item);
                // replace value by json key
                if ($match->hasChildNodes())
                {
                    /** @var DOMElement $child */
                    foreach ($match->childNodes as $child)
                    {
                        if ($child->nodeType == 1)
                        {
                            switch ($child->nodeName)
                            {
                                case 'optgroup':
                                    foreach ($child->childNodes as $nodeChild)
                                        self::replaceOptionSelect($match, $nodeChild, $item);
                                    break;
                                default:
                                    self::replaceOptionSelect($match, $child, $item);
                                    break;
                            }
                        }
                    }
                }
            }
        }
```

Nun sieht alles fein aus.

**Comment by joachimdoerr** [comment]
@eaCe bitte PR mit den changes an phpQuery solange wir das noch nutzen wäre es gut wenn keine deprecated php Methoden mehr drin wären...

**Comment by eaCe** [comment]
@joachimdoerr ich bin nicht sicher ob der ankommen würde:

https://github.com/punkave/phpQuery

Letzter commit vor 6 Jahren, 3 offene PRs seit bis zu 5 Jahren :|
