### ISSUE TITLE
Javascript umbauen

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mblock#69]
Hello

Ich habe mir Letztens überlegt wie man das JS umbauen könnte und wollte dazu noch ein paar Inputs von dir.

Um dem ganze ReInit-Gedöns aus dem Weg zu gehen und um vor allem die Performance zu verbessern, hab ich mir überlegt statt beim verschieben eines Blocks den DOM zu manipulieren, das Ganze mit CSS zu lösen, Flex-sei-Dank.

CSS Flex bietet ja die Möglichkeit Elemente mit der "order" Eigenschaft (siehe https://mzl.la/2nFvApD) visuell die Anordnung zu verändern. Somit würden keine iframes neu geladen werden müssen usw. Auf den ersten Blick scheint mir das eine gute Idee zu sein.

Aber es gibt min. 2 Fragen bzw. Probleme die es zu lösen gilt:

1. die grundsätzliche Frage: muss Mblock auch mit Browser die kein Flex verstehen harmonieren? 
2. und wie merkt sich Mblock die Reihenfolge (hab schon ein paar Ansätze aber bin noch am überlegen)

Falls die Antwort zu 1 ein definitives "ja" ist, ist die Idee fürn A**** (wobei man theoretisch beide Varianten implementieren könnte, je nach Browser).

Was meinst du?

**Comment by joachimdoerr** [comment]
Das verschieben im Dom gewährleistet halt auch, dass die Reihenfolge beim speichern stimmt. 
* Aus meiner Sicht muss MBlock mit allen Browsern laufen, unter denen Redaxo 5 läuft. 
* Die Reihenfolge kommt eben aus dem DOM anhand dessen das das name Attribut von REX_VALUE[id][x][name] von 0 bis n durchgezählt wird.
Ich hab bis jetzt noch keine Performance-Probleme gehabt wo kommt das denn vor?

**Comment by olien** [comment]
> Aus meiner Sicht muss MBlock mit allen Browsern laufen, unter denen Redaxo 5 läuft.

Ich habe mit dem Safari bei einer Sache ein Problem. Aber damit kann ich aktuell leben...

**Comment by ynamite** [comment]
@joachimdoerr ich nutze sehr oft den TinyMCE in Kombination mit Mblock um mehrere Text-Blöcke nebeneinander zu platzieren. Wenn du 10 Tinys hast und dann einen neuen mblock einfügst, verschiebst oder sowas, dann kackt mir der aktuelle Firefox fast ab.

Nicht das ich ein Fan von Tiny bin, aber meine Kunden (normalsterbliche) kommen mit den anderen Editoren schlicht nicht klar. Würde gerne einfach mit Markdown arbeiten, aber das ist eine Wunschvorstellung.

Oder wie macht ihr das? Sorry, dachte das wäre ein generelles Problem :)

Bezüglich Reihenfolge: das Performance-Problem gibt's nur beim anfügen eines weiteren Blocks oder beim Verschieben. Beim initialisieren bzw. neu laden des Blocks könnte die Reihenfolge imo wie bisher im DOM abgebildet werden.

**Comment by joachimdoerr** [comment]
Kannst du mal ein Modul Input geben bei dem das Auftaucht - ich würd es mal testen wollen. Ggf. fällt mir was auf. Ich hab den Tiny noch nie eingesetzt, mit Redactor gibt es keine Probleme selbst, wenn man mehr als 10 Tabs hat in denen 5 Editoren Felder sind.

**Comment by olien** [comment]
Mein Problem (falls Du dir das auch ansehen möchtest) ist hier: https://github.com/FriendsOfREDAXO/bootstrap_helper/blob/master/lib/module/0100_standard_modul/input.inc 

Die Selects werden nicht immer richtig initialisiert.

**Comment by ynamite** [comment]
@joachimdoerr zum Beispiel das hier (nix komplexes), daber das reicht schon. Interessant wegen Redactor, muss ich unbedingt wieder mal anschauen. Hatte mal eine ältere Version aber fand die eher unbrauchbar.

```
<?php

// this modul input example use the mform addon

// base ID
$id = 1;

$mform = new MForm();

// fieldset
$mform->addFieldset('Frage &  Antwort');

$mform->addTextField("$id.0.q", array('label'=>'Frage')); 
$mform->addTextareaField("$id.0.a", array('label'=>'Antwort'))->addAttribute("rows",8)->addAttribute("class", "form-control tinyMCEEditor"); 

echo MBlock::show($id, $mform->show(), array('min'=>1));  

?>
```

**Comment by ynamite** [comment]
Teste übrigens gerade den neuen Tiny aus dem Repo. Der funzt besser bzw. performanter, aber immernoch etwas träge ...

**Comment by joachimdoerr** [comment]
@ynamite stimmt der Tiny ist ziemlich zäh, aber das seh ich eher als problem vom Editor als eines von MBlock.

**Comment by ynamite** [comment]
@joachimdoerr Da stimme ich dir zu, dann liegt's am Tiny. Dachte wie gesagt das sei generell ein Problem. Schau mir mal das Tiny-Gedöns, yay :)
