### ISSUE TITLE
MFORM <> MBLOCK :: REX_MEDIA_X  wird nicht hochgezählt

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mblock#7]
Wenn gleichzeitig MFORM genutzt, wird REX_MEDIA_X nicht hochgezählt.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/commit/702ab16e480b0bb3d1c09defe85192bad097ff26
https://github.com/FriendsOfREDAXO/mblock/commit/dd86ddb2dbc42ce199a4b0c538f026c8cce114ad
