### ISSUE TITLE
LinklistField + '&' im Artikel-Namen wird nicht angezeigt

### ISSUE THREAD

**Issue by crayssnlabs** [FriendsOfREDAXO/mblock#70]
Link-Namen bzw. Artikel-Namen werden nach dem Speichern nicht in der LinkListe angezeigt, wenn sich '&'-Zeichen im Artikel-Namen befindet. Ich konnte das Problem auch soweit einschränken, dass es in in der folgenden Kombination auftritt:
MForm + MBlock + LinklistField + ein '&' Zeichen im Artikel-Namen

**Hier der Modul-Eingabe-Code:**

`$mform = new MForm();
$id = 1;
$mform->addLinklistField(1,array('label'=>'Unter-Menü'));
echo MBlock::show($id, $mform->show(), array('min'=>1,'max'=>5));`

**Hier mein Test-Ergebnis:**

- LinklistField + ein '&' Zeichen -> funktioniert
- MForm + LinklistField + ein '&' Zeichen -> funktioniert
- MBlock + MForm + LinklistField + ein '&' Zeichen -> hier fehlt nach dem Speichern der Artikel-Name, das Value bzw. die ID ist weiterhin da.

Das geht noch, ohne MBlock:
![geht](https://user-images.githubusercontent.com/35770897/37512955-cd276616-2903-11e8-833a-929774d38145.PNG)

Das geht nicht, mit MBlock:
![geht_nicht](https://user-images.githubusercontent.com/35770897/37512956-cd451918-2903-11e8-85cf-4bfbae6acc55.PNG)

**Comment by tbaddade** [comment]
Kannst du bitte testen, ob der Fehler auch ohne mForm passiert!

**Comment by crayssnlabs** [comment]
Leider auch nicht! Habe den Code so getestet:

`$id = 3;
echo MBlock::show($id, REX_LINKLIST[id=3 widget=1], array('min'=>1,'max'=>5));`

![geht_auch_nicht](https://user-images.githubusercontent.com/35770897/37513376-357f54f2-2905-11e8-8703-6bedc7a69f40.PNG)

**Comment by tbaddade** [comment]
Danke fürs probieren.

**Comment by crayssnlabs** [comment]
Danke für die schnelle Reaktion! Bei weiteren Fragen oder für Tests stehen ich gern zur Verfügung.

**Comment by skerbis** [comment]
Problem im Core? Close?

**Comment by joachimdoerr** [comment]
@crayssnlabs versuch mal folgendes ersetze die Zeile `422` in `MBlockSystemButtonReplacer.php`
https://github.com/FriendsOfREDAXO/mblock/blob/master/lib/classes/Replacer/MBlockSystemButtonReplacer.php#L422 mit folgendem Code `$child->nodeValue = htmlentities(self::getLinkInfo($child->getAttribute('value'))['art_name']);`

**Comment by joachimdoerr** [comment]
Ist gefixt: 0ccbc02bfb0ce90d939636cd04d08aab3d93e61d
