### ISSUE TITLE
Call to undefined method DOMText::setAttribute() bei Einsatz von LinklistField

### ISSUE THREAD

**Issue by marcohanke** [FriendsOfREDAXO/mblock#72]
Nutze ich LinklistField bekomme ich ein Whoops 

```
Call to undefined method DOMText::setAttribute()

Error 
…/redaxo/src/addons/mblock/lib/classes/Replacer/MBlockSystemButtonReplacer.php421
```
Getestet mit eigenem Code 
```
<?php
$mform = new MForm();
$mblock = new MForm();


$mform->addFieldset('Metanavigation');
$mform->addLinklistField('1',array('label'=>'Link list'));

$mform->addFieldset('Textspalten');
$mform->addTextAreaField('1.txt1',array('Spalte 1', 'class'=>'redactorEditor2-basic'));
$mform->addTextAreaField('1.txt2',array('Spalte 2', 'class'=>'redactorEditor2-basic'));
$mform->addTextAreaField('1.txt3',array('Spalte 3', 'class'=>'redactorEditor2-basic'));


$mblock->addhtml('<h4>Spalte %%MB_COUNT%%</h4>');
$mblock->addTextField('2.0.headline', array('label'=>'Überschrift'));
// $mblock->addLinklistField(2,array('label'=>'Links'));

$mform->addHtml(MBlock::show(2, $mblock->show(), array('min'=>1,'max'=>6)));
echo $mform->show();

?>
````
aber auch mit dem Beispielcode aus der Doku.

Kann es evtl. sogar an Mform liegen? Dort bekomme ich zwar kein Fehler, aber die Ausgabe bleibt leer...

**Comment by joachimdoerr** [comment]
Nein an MForm liegt das nicht, der Replacer muss ja die Linkliste auffüllen dafür muss er die Objekte schreiben und entsprechend attribute einsetzen. ggf. wurde einer der Artikel gelöscht?

**Comment by marcohanke** [comment]
Problem gelöst. Media und Link Felder dürfen nur numerische Werte enthalten. Außerdem wird die Ausgabe von mblock über ```$mform->addHtml(MBlock::show(2, $mblock->show(), array('min'=>1,'max'=>6)));``` gesteuert. Dadurch gab es durcheinander
