### ISSUE TITLE
"$this can not be used in static methods"

### ISSUE THREAD

**Issue by alexplusde** [FriendsOfREDAXO/mblock#74]
https://github.com/FriendsOfREDAXO/mblock/blob/6e013f19a15d00fe2cbda85c138590018ea46041/vendors/phpQuery/phpQuery/phpQueryObject.php#L2304

Meldet VSCode, wenn man den Ordner öffnet.

**Comment by joachimdoerr** [comment]
PHP query wird für den nächsten major release entfernt werden. ich hatte es eingebaut weil ich dachte es wäre einfacher aber tatsächlich ist es nur ein großer overhead der nicht viel nützt.

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mblock/issues/73

**Comment by joachimdoerr** [comment]
f2410f2d3f85e6e94898a2b14ec931b1ea73c479
