### ISSUE TITLE
Css/jss nur laden wenn nötig

### ISSUE THREAD

**Issue by staabm** [FriendsOfREDAXO/mblock#75]
Wäre es möglich die ganzen css/js includes nur dann zu laden, wenn auch ein mblock in der aktuellen seite enthalten ist?

Aktuell lädt man hier viel zeug und braucht es oft nicht....

Triggered by https://github.com/redaxo/redaxo/issues/1406

**Comment by skerbis** [comment]
evtl. durch den Admin selbst eingrenzen lassen. Da mblock tatsächlich nicht mehr nur in Modulen eingesetzt werden kann, sondern global

**Comment by staabm** [comment]
Ich denke man müsste das über die hook klassen machen können ohne dass irgendwelche manuellen listen gepflegt werden müssen (Vermutung)

Z.b. 
https://github.com/FriendsOfREDAXO/mblock/blob/master/lib/classes/Processor/mblock_rex_form.php

**Comment by joachimdoerr** [comment]
rexform und artikel_slice-edit mehr nicht. Ggf. noch im Frontend wenn man weiß wie man das mit yform in Verbindung bringt. Für yform im backend ist das noch nicht wirklich aufbereitet da müsste ich mal schauen wegen EP's in yform ob ich mich da irgendwie reinhängen könnte für den form builder.

**Comment by alxndr-w** [comment]
Da MBlock zu flexibel einsetzbar ist und Bandbreite heutzutage nicht mehr das entscheidende Kriterium ist, mache ich hier zu. Komplexität erhöhen sehe ich hier nicht.
