### ISSUE TITLE
Neues Theme für Version 3 anfertigen

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mblock#77]
Es soll ein schönes neues Theme her nicht mehr so altbacken wirkt und etwas mehr Flat ist. Ggf. hat ja jemand ein hübschen Gestaltungsvorschlag?

**Comment by olien** [comment]
So habe ich es:

![image](https://user-images.githubusercontent.com/330516/40843451-3e7b4e60-65b1-11e8-8c4e-6616285640b7.png)

**Comment by joachimdoerr** [comment]
Danke @olien für das Beispiel ich sehe aber für V3 eher eine limitierteren Skin mit weniger platzverschwendenden Elementen, ggf. + und - von Blöcken nur bei hover erscheinend + Drag-Drop Feld nicht mehr als so eine Fette leiste. Also alles mehr Flat. Hat jemand aus der Community lust hier etwas zu gestalten? Ich wäre für Impressionen dankbar.

**Comment by shauste** [comment]
@joachimdoerr Hi Joachim, würde mich hier für eine Gestaltung gerne einbringen. Wäre prima, wenn Du mit die aktuelle Version als Screenshot hinterlässt.

**Comment by joachimdoerr** [comment]
@shauste find ich super ich persönlich finde den style vom craft und auch von sulu ganz hübsch aber auch die minimale Variante von [grapesjs](http://grapesjs.com/demo.html) schaut interessant aus. 
grapesjs:
![bildschirmfoto 2018-06-08 um 14 02 07](https://user-images.githubusercontent.com/1191549/41157058-a47812e8-6b24-11e8-9434-fac3cac92ef2.png)
Sulu: 
![bildschirmfoto 2018-06-08 um 14 03 55](https://user-images.githubusercontent.com/1191549/41157105-d2f392dc-6b24-11e8-9624-35c5c721038e.png)
craftcms:

**Comment by joachimdoerr** [comment]
@shauste hier der aktuelle MBlock style mit nested MBlocks
![bildschirmfoto 2018-06-08 um 14 07 57](https://user-images.githubusercontent.com/1191549/41157264-6c7e438e-6b25-11e8-8e6d-9d7182e6a326.png)

**Comment by skerbis** [comment]
Deine jetzige Variante ist dem Aufbau von Sulu schon sehr ähnlich, wenn man sich von dem grün verabschiedet und die fieldsets styled

**Comment by shauste** [comment]
@joachimdoerr Morgen, hier kommt ein Update, etwas interaktiver: https://marvelapp.com/3i17dbh
Meine Anmerkungen:
Neben der Einrückung würde ich die farbliche Visualisierung der Ebene belassen. Auch das Spacing würde ich aus 2 Gründen nicht verknappen: 1. Passende Erscheinung im gesamten Redaxo-System (kein Fremdkörper). 2. Angenehme Drag and Drop-Funktion.

**Comment by joachimdoerr** [comment]
@shauste Ich finde die Reduktion der SubMBlocks schon sehr gelungen! Das die Hauptblöcke so schließbar sind das meinst du mit Fold/Unfold?

Sollte der Hauptblock nicht auch so funktionieren, dass die Steurungselemente erst beim hover in den Block erscheinen? 

Das mit den Abständen ist so eine Sache. Hat man massig Blocks wird es sehr unübersichtlich, eventuell wäre ein dynamisches anpassen der abstände bei hoher Blockanzahl die Lösung.

**Comment by shauste** [comment]
@joachimdoerr Ich denke, dass die Klapp-Funktion (Fold/Unfold) das Problem des Platzes optional löst.

Die Navigation des Hauptblocks würde ich stets anzeigen. Zum einen flackert es dann nicht ständig, wenn zwischen den Blöcken navigiert wird, zum anderen ist die Hierarchie schnell erkennbar (zusätzliche Orientierung)

**Comment by joachimdoerr** [comment]
Die frage ist ob es wirklich massiv störend wäre mit dem "flackern". Ein kurzer delay und smoothes faden würden das sicher vermeiden. 
Zur Hilfe für die Orientierung 1+ das ist ein starkes Argument das für den verbleib der Steuerelemente spricht.

**Comment by shauste** [comment]
@joachimdoerr Hab die Screens aktualisiert und eine Idee eines Indikators (gleichzeitig Fold/Unfold) für die Subblöcke integriert: https://marvelapp.com/3i17dbh

Was meinst Du?

**Comment by joachimdoerr** [comment]
@shauste find ich praktisch es sollte nur konsequenterweise dann auch für die Hauptblöcke vorhanden sein. die frage hier ist aber ob die Modul-Label-Area der richtige Platz ist. 
![bildschirmfoto 2018-06-11 um 10 11 11](https://user-images.githubusercontent.com/1191549/41219816-cf4e50e4-6d5f-11e8-8063-eb9c75c4e065.png)
Wir müssen ja auch bedenken das man mehrere MBlocks pro Modul anlegen kann. Wie verhält es sich damit, hier 2 oder 3 Haupt-MBlöcke (Level1) platziert werden und diese jeweils nochmals 1-2 Sub-MBlöcke haben (Level2) dann wird das mit dem Counter und der Platzierung schwierig.

**Comment by joachimdoerr** [comment]
@shauste was wir noch nicht berücksichtigt haben ist dass MBlock sowohl horizontal als auch vertikale Blöcke Supporten sollte: https://github.com/FriendsOfREDAXO/mblock/issues/79

**Comment by joachimdoerr** [comment]
61184deacd22c60e63e1516e1563781d82a29560
