### ISSUE TITLE
Nested MBlocks

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mblock#78]
Für V3 soll MBlock nested MBlöcke zulassen. Das ist tricky aber sicher irgendwie möglich.

**Comment by joachimdoerr** [comment]
Der erste Schritt ist getan 77381400cae67dbb449e348f07711573d2ced560
Nun fehlt nur noch der JS Part.

**Comment by joachimdoerr** [comment]
Ich hab mir das zu einfach vorgestellt es gibt noch diverse kleine Probleme die nun nach und nach beim testen auftauchen ich denke das ganze wird noch etwas komplexer ausfallen als erwartet. ich denke es ist nicht mit "ergänzen" getan, das ganze bringt konzeptionelle Anpassungen mit sich ohne die es nicht funktionieren kann.

**Comment by joachimdoerr** [comment]
Nach dem ich das gesamte php umgekrempelt habe ist nun der php tatsächlich fast abgeschlossen. Es fehlt nur noch für rex_form und yform die Möglichkeit die regex für die name manipulation anzupassen.  Danach steht der JS Part an. Ich gehe mal davon aus dass ich auch hier keine community Hilfe erwarten kann? Eigentlich ist es schade, dass sie die Community so "gering" am Entwicklungsprozess der Addons hier beteiligt.

**Comment by ynamite** [comment]
@joachimdoerr 
Ich würde gerne mehr aktiv mithelfen, wirklich, aber ich komm einfach kaum dazu :/ ich bin selbständig/allein und wenn ich mal nicht vor dem Bildschirm an Kundenprojekten arbeite bin ich froh einfach mal nichts tun zu müssen bzw. Schlaf nachzuholen. 
Aber ich verstehe dich völlig und da ich wahnsinnig von deiner Arbeit an mform, mblock und etlichen anderen Addons von dir und aus der Community profitiere, ist es mir schon lange ein Anliegen mitzuhelfen. Allerdings verhält es sich ähnlich wie mit gut gemeinten Neujahresvorsätzen. Meist bleibt es bei der Idee/beim Wunsch.

Im ernst, ich möchte gerne helfen, ich frage mich nur gerade wie/wann.

**Comment by joachimdoerr** [comment]
@ynamite du hast ja schon an MBlock mit gebaut, und ohne deine Hilfe gäbe es keine vernünftigen JS Events. Also kein Stress ;) ich bin nur etwas frustriert, mir geht es ja nicht unbedingt um Coding-Unterstützung sondern auch ums Feedback, um das Mitdenken etc. Man baut so ein Addon welches ja schon eine recht hohe Relevanz hat in der Community, will es dann für die Community auf den "nächsten Level" heben und der Community ist es einfach scheiß egal. Ich meine ich hab die fettesten und geilsten Features in Milestone 3 angekündigt die viele Leute sich schon lange wünschen -> keine Reaktion... das ist schon strange. Gut von der Redaxo Community ist man es ja schon gewohnt das da wenig konstruktiv zurück kommt aber mit so wenig hätte ich nicht gerechnet. Man fragt sich dann ernsthaft ob man überhaupt noch so viel Energie reinstecken will.

**Comment by tbaddade** [comment]
Hier #77 kann man erkennen was du genau vorhast. Diese nested Blöcke gehen dann unendlich in {n}-Tiefe?

**Comment by shauste** [comment]
Ich würde lediglich 1 Ebene zulassen.

**Comment by tbaddade** [comment]
> Die Frage ist ob das sinn macht, aus meiner Sicht sind maximal 1-2 Level sinnvoll und handlebar.

Die Daten-Beispiele die ich bisher sah, würde ich vermutlich eher via YForm abbilden. Grad weil die Übersicht verloren gehen könnte. Bin gespannt wie das wird.

**Comment by joachimdoerr** [comment]
@tbaddade ich hatte kürzlich selbst das Szenario das ich im MBlock gerne ein MBlock gehabt hätte: Szenario Slider mit Hintergrundbild + Headline + Leadtext + optional 1-3 Buttons. 
Die Slider Items mit MBlock abbilden ist easy, Bild, Headline, Subheadline ist kein Problem nur die Buttons... die hatte ich dann Fest verdrahtet hätte in dem Fall aber eigentlich gerne ein SubMBlock gehabt.

**Comment by darwin26** [comment]
> @tbaddade ich hatte kürzlich selbst das Szenario das ich im MBlock gerne ein MBlock gehabt hätte: Szenario Slider mit Hintergrundbild + Headline + Leadtext + optional 1-3 Buttons.
> Die Slider Items mit MBlock abbilden ist easy, Bild, Headline, Subheadline ist kein Problem nur die Buttons... die hatte ich dann Fest verdrahtet hätte in dem Fall aber eigentlich gerne ein SubMBlock gehabt.

uiii - nested MBlocks / SubBlocks -> jep... das wäre ein Szenario (mehrere Slider/Items Buttons).
Bin schon gespannt... kann man nested schon testen (evtl . Beispiel zur Hand?) - Danke

**Comment by joachimdoerr** [comment]
Läuft leider noch nicht so ganz sauber es fehlt noch das JS dafür. Das PHP ist aber schon fertig und kommt damit problemlos klar.

**Comment by joachimdoerr** [comment]
593538299b1cc7b6278259a8830df98144a02b84

**Comment by eaCe** [comment]
Gibt es inzwischen ein Beispiel hierzu?
