### ISSUE TITLE
MBlöcke horizontal und vertikal

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mblock#79]
Damit MBlöcke auch als Columns positioniert werden können. In der Vertikalen wäre es schön wenn die Breite der Blöcke durch die Formulare beeinflusst werden könnte. Idee von : @skerbis danke dafür find ich super.

**Comment by skerbis** [comment]
Jetzt bin ich et wieder Schuld ;-)

**Comment by shauste** [comment]
@joachimdoerr Welchen Zweck erfüllt die vertikale Darstellung?

**Comment by joachimdoerr** [comment]
@shauste ich hab den Wunsch öfters zugetragen bekommen, viele wollen so Grids in der Eingabe optisch besser anzeigen können:
Level1 -> Grid Columns (vertikal)
Die Nested Sub-MBlocks liefern dazu dann die Möglichkeit im Grid-Column rows setzen zu können
Level2 -> Rows im Column (horizontal)

**Comment by joachimdoerr** [comment]
Die Frage ist ja ob das sinn macht, das Redaxo Modul Input feld ist sowieso nicht sehr breit wenn man darin dann noch mit Columns für die Eingabe arbeitet wird es eng - mehr als 2 nebeneinander kann man glaub ich sowieso vergessen. Ich glaube da wäre ein Tab Support besser.

**Comment by joachimdoerr** [comment]
Ich hab das feature erstmal in Milestone 3.1.0 gesetzt, das ist doch zu aufwändig alles für Milestone 3 zu realisieren

**Comment by joachimdoerr** [comment]
Ich streiche auch dieses Feature von der Liste es ist zu Aufwändig und deswegen unrealistisch das realisieren zu wollen. Zudem ist das Interesse auch hierfür minimal.
