### ISSUE TITLE
Modulbeispiel ohne mForm

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#8]
Hallo Joachim,

da ich aktuell alle Module (noch) ohne mForm habe würde ich mich über ein einfaches Beispiel eines Moduls ohne mForm freuen.

LG
Oliver

**Comment by joachimdoerr** [comment]
Salü, warum das denn? du hattet doch früher immer mform eingesetzt. 

Ein Beispiel kann man schon machen... hab aber noch paar andere Tasks.

**Comment by olien** [comment]
Aktuell habe ich die Modulsammlung ja ohne mForm (war schneller als Du :-)) realisiert. Dort könnt ich das evtl. gebrauchen ohne alles auf mForm umbauen zu müssen... Mache ich vielleicht später.

**Comment by tbaddade** [comment]
Ich fände es gut, wenn du das vorziehen könntest.

**Comment by tbaddade** [comment]
Bsp.

```php
<?php

// base ID
$id = 1;

$form = '
<fieldset class="form-horizontal">
    <legend>Inhalt</legend>
    <div class="form-group">
        <label class="col-md-3 control-label">Überschrift</label>
        <div class="col-md-9">
            <input class="form-control" name="REX_INPUT_VALUE[1][0][heading]" value="" type="text" />
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-3 control-label">Intro</label>
        <div class="col-md-9">
            <textarea class="form-control" name="REX_INPUT_VALUE[1][0][intro]" rows="10"></textarea>
        </div>
    </div>
</fieldset>
';

// parse form
echo MBlock::show($id, $form);

```

**Comment by tyrant88** [comment]
Da bekomme ich beim Klick auf das "+" im Moduleditieren die Javascript Fehlermeldung:
Error: no such method 'destory' for sortable widget instance

Bin aber auch auf einem Entwicklungsystem unterwegs, vielleicht schießt da was anderes quer...
Muss erst noch anderes erledigen.
Danke soweit.

**Comment by joachimdoerr** [comment]
@tbaddade  Danke fürs Beispiel ich werd das in die Beispiel Sammlung im Addon integrieren wenn du nichts dagegen hast. Das sollte dann den Issue erledigen.

**Comment by joachimdoerr** [comment]
@tyrant88 wenn das problem an MBlock liegen sollte wäre es toll wenn du mich mal auf den System lassen könntest, dann würde ich ggf. den Fehler sehen und verstehen können. So kann ich da erstmal nicht feststellen woran das liegt.

**Comment by tyrant88** [comment]
Okay, erstmal Entwarnung ich hab es auf einem anderen R installiert da geht es.
D.h. allerdings für mich in meiner aktuellen Entwicklung ist was im Argen....

**Comment by tbaddade** [comment]
@joachimdoerr Du kannst das Bsp. gern verwenden, aber ich würde das erst veröffentlichen, wenn auch das #11 und #12 erledigt sind.

**Comment by tyrant88** [comment]
Ah, ich hatte eine alte jQuery.ui.js Bibliothek im meinem addon drin. Jetzt geht es.

Aber dein Plugin jquery.fn.sortable.min.js überschreibt die normale sortable-Funktion. Jetzt haben die Effekte andere CSS-Klassen ("ghost"?) als vorher!

**Comment by joachimdoerr** [comment]
Welche Sortable Funktion nutzt du denn zudem?

**Comment by tyrant88** [comment]
Ich nehme an, die ist in der Standard Backend jquery.ui: jquery-ui.custom.min.js

**Comment by joachimdoerr** [comment]
welches addon nutzt denn die jQuery ui? Oder hast du die einfach so eingebunden. Am besten du gibst mal eine Liste an Addons die du nutzt damit ich das prüfen kann. Eventuell kann ich ja den sortable einfach umbenennen um die Konflikte zu umgehen.

**Comment by tyrant88** [comment]
Ja, ich denke mal Umbenennen wäre gut. Im Moment wird ja was vom core überschrieben - eben eine Funktion der jquery-ui.custom.min.js des Backends, also wird das ja jedem anderem Addon auch so gehen, nicht nur meinem, oder?

**Comment by joachimdoerr** [comment]
Ja, das ist jedenfalls ein super Hinweis, dank dir - ich werd das entsprechend umbenennen, damit es zu keinem Konflikt mehr kommen kann.

**Comment by joachimdoerr** [comment]
done.
