### ISSUE TITLE
Default Values für alle + mblöcke 

### ISSUE THREAD

**Issue by joachimdoerr** [FriendsOfREDAXO/mblock#82]
Ggf. mit data-mblock-default attribute realisieren.

**Comment by pschuchmann** [comment]
:+1: weil ich gerade ein Issue dazu eröffnen wollte ;)

**Comment by madiko** [comment]
Super, wollte auch gerade einen issue dazu aufmachen. Danke Joachim!

**Comment by novinet-dsteffen** [comment]
Dafür haben wir evtl. eine Lösung mit einem zusätzlichen Addon, welches auf MBlock und MForm aufbaut. https://github.com/novinet-git/nv_modulesettings

**Comment by pschuchmann** [comment]
Danke dir @novinet-dsteffen. Wenn ich das richtig verstanden habe, setzt das Addon wiederkehrende Optionen an eine MForm dran, oder?

**Comment by novinet-git** [comment]
@pschuchmann korrekt und zwar im "zwiebelprinzip" - es gibt coresettings des addons, dann settings für das projekt und dann settings für ein einzelnes modul

**Comment by novinet-dsteffen** [comment]
@pschuchmann korrekt und zwar im "zwiebelprinzip" - es gibt coresettings des addons, dann settings für das projekt und dann settings für ein einzelnes modul

**Comment by pschuchmann** [comment]
Ah, ok, dann ist das eher ein grundsätzliches Feature. hier geht es eher darum, dass du mit MForm für jeden Input einen Default anlegen kannst. Verwendest du diese MForm dann in MBlock, werden diese Default Values aber wieder raus geworfen. 

Ich denke, da wollte @joachimdoerr per Datenattribut gegensteuern, korrigiere mich, wenn ich falsch liege.

**Comment by alxndr-w** [comment]
https://github.com/FriendsOfREDAXO/mform/issues/185
