### ISSUE TITLE
Reduzierte Ansicht

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mblock#84]
Blöcke bei sehr langen Formularen optional zusammenklappen lassen

**Comment by joachimdoerr** [comment]
Hier ist die Frage ob der Gesamte Inhalt geschlossen werden sollte oder nur ein Teil sichtbar ist.

**Comment by skerbis** [comment]
In der Höhe reduzieren, damit man einen Einblick erhält was drin steckt, denke ich. Sonst müsste man den Redakteur zwingen einen Titel zu hinterlegen, was zu bürokratisch ist.
