### ISSUE TITLE
Sortierung killt TinyMCE Inhalt

### ISSUE THREAD

**Issue by godsdog** [FriendsOfREDAXO/mblock#89]
Hallo, in der aktuellen Version wird bei mir der sichtbare Inhalt im TinyMCE Textfeld nach dem Sortieren von MBlock Blöcken gelöscht. Man kann dann keinen Inhalt mehr im TinyMCE Feld sehen und erstellen.

Im Quellcode wird anscheinend der Inhalt vom TinyMCE Iframe im Head und Body gelöscht.

Hier ein Beispiel:
`
$mform = new MForm();
$mform->addFieldset('Test');
$mform->addTextAreaField("1.0.text", array('label'=>'Text', 'class'=>'tinyMCEEditor'));
echo MBlock::show(1, $mform->show(), array('min'=>1,'max'=>10));
`

Das passiert nur bei dem Block, der neu sortiert wird. Die restlichen Blöcken, welche dann auch sortiert werden, sind nicht davon betroffen.

Im TinyMCE Addon finde ich folgendes:
/assets/addons/tinymce4/tinymce4_init.de.js

`$(document).on('ready pjax:success',function() {
    // Erst instanzen zerstören, erforderlich für "Block Übernehmen"
    window.setTimeout(function() {
        tinymce4_remove();
        tinymce4_init();
    }, 100);

    if (typeof mblock_module === 'object' && !document.tinymce_mblock_initialized) {
        document.tinymce_mblock_initialized = true;

        mblock_module.registerCallback('reindex_end', function() {
            if (mblock_module.lastAction == 'add_item' || mblock_module.lastAction == 'sort') {
                mblock_module.affectedItem.find('.mce-initialized').removeClass('mce-initialized').show();
                mblock_module.affectedItem.find('.mce-tinymce.mce-container').remove();
                tinymce4_init();
            }
        });
    }
});`

Müsste doch eigentlich damit funktionieren oder?:

` mblock_module.registerCallback('reindex_end', function() {
            if (mblock_module.lastAction == 'add_item' || mblock_module.lastAction == 'sort') {
                mblock_module.affectedItem.find('.mce-initialized').removeClass('mce-initialized').show();
                mblock_module.affectedItem.find('.mce-tinymce.mce-container').remove();
                tinymce4_init();
            }`

**Comment by godsdog** [comment]
Ist ein TinyMCE Issue:
https://github.com/FriendsOfREDAXO/tinymce4/issues/56

Habe dort auch den Fix beschrieben.

**Comment by joachimdoerr** [comment]
Dann auch hier closed weil kein MBlock issue.
