### ISSUE TITLE
Scrollen zum neuen Block

### ISSUE THREAD

**Issue by skerbis** [FriendsOfREDAXO/mblock#9]
Wenn ein neuer Block erstellt (dupliziert wird) , macht es Sinn, gerade bei langen Formularen, dass zum neuen Block gesprungen wird.

**Comment by joachimdoerr** [comment]
Done. https://github.com/FriendsOfREDAXO/mblock/commit/c50ee0cb82eff78c5bcede8fba38e486f6bf4f39
