### ISSUE TITLE
Upgrade von 1.7 auf 2.x

### ISSUE THREAD

**Issue by tbaddade** [FriendsOfREDAXO/mblock#91]
Ich hatte ein `rex_select` in einer Moduleingabe und bekam diese Whoops Meldung

> Argument 2 passed to MBlockFormItemDecorator::replaceOptionSelect() must be an instance of DOMElement, instance of DOMText given

Das liegt daran, [dass hier](https://github.com/FriendsOfREDAXO/mblock/blob/master/lib/MBlock/Decorator/MBlockFormItemDecorator.php#L80) als nodeName ein `#text` ankam. 
Ein Änderung von `default` auf `case 'option':` schaffte Abhilfe.

Ob das so richtig ist, müsstest du prüfen. Eventuell landen dort auch noch andere nodeNames die du aber durchschleusen willst.

**Comment by tbaddade** [comment]
Erstelle ein `rex_select` mit ein paar Optionen. Dann sollte der Fehler auftauchen. Eventuell Slice speichern und wieder öffnen.

**Comment by tbaddade** [comment]
Ich weiß nicht ob du den Link wahrgenommen hast. Das ist die Zeile um die es geht
https://github.com/FriendsOfREDAXO/mblock/blob/4fc1e9c7d10c421b3890f4402f3564497502e546/lib/MBlock/Decorator/MBlockFormItemDecorator.php#L80

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/mblock/pull/96
