### ISSUE TITLE
Darstellungsfehler bei addMediaField / addMedialistField mblock Version 2.2.1

### ISSUE THREAD

**Issue by ynamite** [FriendsOfREDAXO/mblock#92]
Mit mblock Version 2.2.1 kommt es innerhalb eines mblocks, ebenfalls bei Verwendung von addMediaField oder addMedialistField, zu Darstellungsfehler, weil irgendein ein Tag nicht geöffnet/geschlossen wird (scheinbar wird entweder von mform oder mblock ein zusätzliches HTML-/Body-Tag um das Media/Medialist Feld gelegt)

```<div class="col-sm-10"><html><body><div class="rex-js-widget rex-js-widget-medialist rex-js-widget-preview rex-js-widget-preview-media-manager">...```

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/mform/issues/144

Das war ein MForm Problem ist mit dem Fix in Version 5.2.1 behoben.
