### ISSUE TITLE
pjax und rex:ready

### ISSUE THREAD

**Issue by dergel** [FriendsOfREDAXO/mblock#94]
Im Moment reagiert und nutzt mblock pjax. Aber richtiger ist es wenn rex:ready genutzt wird, auch wenn zu z.b. neue mblöcke initialisiert werden. die entsprechenden editoren sollten dann entsprechend darauf reagieren. Schaut mal bei 

https://github.com/FriendsOfREDAXO/cke5/pull/58

nach..

**Comment by skerbis** [comment]
Dem stimme ich zu

**Comment by joachimdoerr** [comment]
https://github.com/FriendsOfREDAXO/cke5/pull/58

**Comment by joachimdoerr** [comment]
3b85964e9ee04aa6a9ac5f054ea4caf387d8bae5
dae8062b4e8ae2e162c3f6fbb1289bbd2740f757
d5e4ef176ddc64d5c5ca4fa379c91d4251ecb37a
81962271ef2a93c4f4c71663ffb58cec05e91564
dacd5b50052a96219ba5a7c990c2a7efe96b9638
9bee06c695256faaa36547f25b088aeae8ac7cad

**Comment by fietstouring** [comment]
beim Hinzufügen neuer Blöcke wird ein rex:ready getriggert aber nicht beim Sortieren. 
wenn Du da auch den Event triggern könntest, wäre super, da können die Editoren darauf reagieren. In meinem Fall hab ichs für CKEditor 4 hinbekommen, dass Sortieren über die Pfeile funktioniert.

**Comment by fietstouring** [comment]
und noch ne andere Frage in diesem Zusammenhang:
der Timeout beim Sortieren hat nur optische Gründe oder andere?

**Comment by tbaddade** [comment]
Es wäre sinnvoller ein neues Issue aufzumachen.
