### ISSUE TITLE
Probleme mit PHP 7.2.x?

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#95]
Aus dem Slack

<img width="342" alt="image" src="https://user-images.githubusercontent.com/330516/45770165-eb37d100-bc41-11e8-9ef9-ae92e59d4c27.png">

**Comment by skerbis** [comment]
Fehler? Syslog?

**Comment by olien** [comment]
`sizeof() [<a href='https://php.net/manual/function.sizeof'>function.sizeof</a>]: Parameter must be an array or an object that implements Countable

redaxo/src/addons/mform/lib/classes/MFormElements.php

Zeile 71 und 68`


mehr habe ich nicht im chat gefunden

**Comment by skerbis** [comment]
Schon die  neue Version installiert?

**Comment by tbaddade** [comment]
> redaxo/src/addons/mform/lib/classes/MFormElements.php

Falsches Repo?

**Comment by skerbis** [comment]
https://github.com/FriendsOfREDAXO/mform/blob/master/CHANGELOG.md 
ist fixed
