### ISSUE TITLE
Warning

### ISSUE THREAD

**Issue by olien** [FriendsOfREDAXO/mblock#98]
Warning: DOMElement::setAttribute() expects parameter 2 to be string, array given in /Users/abc/def/schule/redaxo/src/addons/mblock/lib/MBlock/Decorator/MBlockFormItemDecorator.php on line 160

MBlock 2.2.3
REDAXO 5.6.4
PHP 7.2.7 

Die Warning kommt sobald ich ein Multiselect SQL Feld (MForm) in der Eingabe habe.

```
$mform->addMultiSelectField("$id.0.kalender");
$mform->addOption('Alle', 'alle');
$mform->setSize(10);
$mform->setLabel('Kalender');
$mform->setSqlOptions('select id, name_1 AS name from rex_sked_categories ORDER BY name');

```

**Comment by skerbis** [comment]
welche mform-version?

**Comment by olien** [comment]
mform: 5.2.2

**Comment by tbaddade** [comment]
Kommt die Warning auch ohne MForm?

**Comment by olien** [comment]
das kann ich aktuell gerade nicht sagen.. in dem modul ist soviel mform, dass ich das nicht mal eben testen kann. wenn ich die oben angegebenen zeilen entferne kommt keine warning...

**Comment by olien** [comment]
hm. Für das Projekt nutze ich jetzt `error_reporting(0);`

**Comment by joachimdoerr** [comment]
8bd8d15318d7ee9e6f020c7b2e1240b49032cf8d
add27412a3f674571b6bb85b0cf02d798c7f24ed
